/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsRuleCreateParams
 */
export interface AnalyticsRuleCreateParams {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleCreateParams
     */
    destinationCollection?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRuleCreateParams
     */
    limit?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsRuleCreateParams
     */
    captureSearchRequests?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalyticsRuleCreateParams
     */
    metaFields?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticsRuleCreateParams
     */
    expandQuery?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleCreateParams
     */
    counterField?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsRuleCreateParams
     */
    weight?: number;
}

/**
 * Check if a given object implements the AnalyticsRuleCreateParams interface.
 */
export function instanceOfAnalyticsRuleCreateParams(value: object): value is AnalyticsRuleCreateParams {
    return true;
}

export function AnalyticsRuleCreateParamsFromJSON(json: any): AnalyticsRuleCreateParams {
    return AnalyticsRuleCreateParamsFromJSONTyped(json, false);
}

export function AnalyticsRuleCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRuleCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationCollection': json['destination_collection'] == null ? undefined : json['destination_collection'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'captureSearchRequests': json['capture_search_requests'] == null ? undefined : json['capture_search_requests'],
        'metaFields': json['meta_fields'] == null ? undefined : json['meta_fields'],
        'expandQuery': json['expand_query'] == null ? undefined : json['expand_query'],
        'counterField': json['counter_field'] == null ? undefined : json['counter_field'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function AnalyticsRuleCreateParamsToJSON(json: any): AnalyticsRuleCreateParams {
    return AnalyticsRuleCreateParamsToJSONTyped(json, false);
}

export function AnalyticsRuleCreateParamsToJSONTyped(value?: AnalyticsRuleCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destination_collection': value['destinationCollection'],
        'limit': value['limit'],
        'capture_search_requests': value['captureSearchRequests'],
        'meta_fields': value['metaFields'],
        'expand_query': value['expandQuery'],
        'counter_field': value['counterField'],
        'weight': value['weight'],
    };
}

