/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsEventsResponseEventsInner } from './AnalyticsEventsResponseEventsInner';
import {
    AnalyticsEventsResponseEventsInnerFromJSON,
    AnalyticsEventsResponseEventsInnerFromJSONTyped,
    AnalyticsEventsResponseEventsInnerToJSON,
    AnalyticsEventsResponseEventsInnerToJSONTyped,
} from './AnalyticsEventsResponseEventsInner';

/**
 * 
 * @export
 * @interface AnalyticsEventsResponse
 */
export interface AnalyticsEventsResponse {
    /**
     * 
     * @type {Array<AnalyticsEventsResponseEventsInner>}
     * @memberof AnalyticsEventsResponse
     */
    events: Array<AnalyticsEventsResponseEventsInner>;
}

/**
 * Check if a given object implements the AnalyticsEventsResponse interface.
 */
export function instanceOfAnalyticsEventsResponse(value: object): value is AnalyticsEventsResponse {
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function AnalyticsEventsResponseFromJSON(json: any): AnalyticsEventsResponse {
    return AnalyticsEventsResponseFromJSONTyped(json, false);
}

export function AnalyticsEventsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsEventsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'events': ((json['events'] as Array<any>).map(AnalyticsEventsResponseEventsInnerFromJSON)),
    };
}

export function AnalyticsEventsResponseToJSON(json: any): AnalyticsEventsResponse {
    return AnalyticsEventsResponseToJSONTyped(json, false);
}

export function AnalyticsEventsResponseToJSONTyped(value?: AnalyticsEventsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': ((value['events'] as Array<any>).map(AnalyticsEventsResponseEventsInnerToJSON)),
    };
}

