/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AnalyticsRuleParameters } from './AnalyticsRuleParameters';
import {
    AnalyticsRuleParametersFromJSON,
    AnalyticsRuleParametersFromJSONTyped,
    AnalyticsRuleParametersToJSON,
} from './AnalyticsRuleParameters';

/**
 * 
 * @export
 * @interface AnalyticsRuleSchema
 */
export interface AnalyticsRuleSchema {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleSchema
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleSchema
     */
    type: string;
    /**
     * 
     * @type {AnalyticsRuleParameters}
     * @memberof AnalyticsRuleSchema
     */
    params: AnalyticsRuleParameters;
}

/**
 * Check if a given object implements the AnalyticsRuleSchema interface.
 */
export function instanceOfAnalyticsRuleSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "params" in value;

    return isInstance;
}

export function AnalyticsRuleSchemaFromJSON(json: any): AnalyticsRuleSchema {
    return AnalyticsRuleSchemaFromJSONTyped(json, false);
}

export function AnalyticsRuleSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRuleSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'params': AnalyticsRuleParametersFromJSON(json['params']),
    };
}

export function AnalyticsRuleSchemaToJSON(value?: AnalyticsRuleSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'params': AnalyticsRuleParametersToJSON(value.params),
    };
}

