/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticsRuleType } from './AnalyticsRuleType';
import {
    AnalyticsRuleTypeFromJSON,
    AnalyticsRuleTypeFromJSONTyped,
    AnalyticsRuleTypeToJSON,
    AnalyticsRuleTypeToJSONTyped,
} from './AnalyticsRuleType';
import type { AnalyticsRuleCreateParams } from './AnalyticsRuleCreateParams';
import {
    AnalyticsRuleCreateParamsFromJSON,
    AnalyticsRuleCreateParamsFromJSONTyped,
    AnalyticsRuleCreateParamsToJSON,
    AnalyticsRuleCreateParamsToJSONTyped,
} from './AnalyticsRuleCreateParams';

/**
 * 
 * @export
 * @interface AnalyticsRuleCreate
 */
export interface AnalyticsRuleCreate {
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleCreate
     */
    name: string;
    /**
     * 
     * @type {AnalyticsRuleType}
     * @memberof AnalyticsRuleCreate
     */
    type: AnalyticsRuleType;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleCreate
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleCreate
     */
    eventType: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticsRuleCreate
     */
    ruleTag?: string;
    /**
     * 
     * @type {AnalyticsRuleCreateParams}
     * @memberof AnalyticsRuleCreate
     */
    params?: AnalyticsRuleCreateParams;
}



/**
 * Check if a given object implements the AnalyticsRuleCreate interface.
 */
export function instanceOfAnalyticsRuleCreate(value: object): value is AnalyticsRuleCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('collection' in value) || value['collection'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    return true;
}

export function AnalyticsRuleCreateFromJSON(json: any): AnalyticsRuleCreate {
    return AnalyticsRuleCreateFromJSONTyped(json, false);
}

export function AnalyticsRuleCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRuleCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': AnalyticsRuleTypeFromJSON(json['type']),
        'collection': json['collection'],
        'eventType': json['event_type'],
        'ruleTag': json['rule_tag'] == null ? undefined : json['rule_tag'],
        'params': json['params'] == null ? undefined : AnalyticsRuleCreateParamsFromJSON(json['params']),
    };
}

export function AnalyticsRuleCreateToJSON(json: any): AnalyticsRuleCreate {
    return AnalyticsRuleCreateToJSONTyped(json, false);
}

export function AnalyticsRuleCreateToJSONTyped(value?: AnalyticsRuleCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': AnalyticsRuleTypeToJSON(value['type']),
        'collection': value['collection'],
        'event_type': value['eventType'],
        'rule_tag': value['ruleTag'],
        'params': AnalyticsRuleCreateParamsToJSON(value['params']),
    };
}

