/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AnalyticsRuleType = {
    PopularQueries: 'popular_queries',
    NohitsQueries: 'nohits_queries',
    Counter: 'counter',
    Log: 'log'
} as const;
export type AnalyticsRuleType = typeof AnalyticsRuleType[keyof typeof AnalyticsRuleType];


export function instanceOfAnalyticsRuleType(value: any): boolean {
    for (const key in AnalyticsRuleType) {
        if (Object.prototype.hasOwnProperty.call(AnalyticsRuleType, key)) {
            if (AnalyticsRuleType[key as keyof typeof AnalyticsRuleType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AnalyticsRuleTypeFromJSON(json: any): AnalyticsRuleType {
    return AnalyticsRuleTypeFromJSONTyped(json, false);
}

export function AnalyticsRuleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRuleType {
    return json as AnalyticsRuleType;
}

export function AnalyticsRuleTypeToJSON(value?: AnalyticsRuleType | null): any {
    return value as any;
}

export function AnalyticsRuleTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): AnalyticsRuleType {
    return value as AnalyticsRuleType;
}

