/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsRuleParametersSource
 */
export interface AnalyticsRuleParametersSource {
    /**
     * 
     * @type {Array<string>}
     * @memberof AnalyticsRuleParametersSource
     */
    collections?: Array<string>;
}

/**
 * Check if a given object implements the AnalyticsRuleParametersSource interface.
 */
export function instanceOfAnalyticsRuleParametersSource(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AnalyticsRuleParametersSourceFromJSON(json: any): AnalyticsRuleParametersSource {
    return AnalyticsRuleParametersSourceFromJSONTyped(json, false);
}

export function AnalyticsRuleParametersSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsRuleParametersSource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'collections': !exists(json, 'collections') ? undefined : json['collections'],
    };
}

export function AnalyticsRuleParametersSourceToJSON(value?: AnalyticsRuleParametersSource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'collections': value.collections,
    };
}

