/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AnalyticsStatus
 */
export interface AnalyticsStatus {
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    popularPrefixQueries?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    nohitsPrefixQueries?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    logPrefixQueries?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    queryLogEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    queryCounterEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    docLogEvents?: number;
    /**
     * 
     * @type {number}
     * @memberof AnalyticsStatus
     */
    docCounterEvents?: number;
}

/**
 * Check if a given object implements the AnalyticsStatus interface.
 */
export function instanceOfAnalyticsStatus(value: object): value is AnalyticsStatus {
    return true;
}

export function AnalyticsStatusFromJSON(json: any): AnalyticsStatus {
    return AnalyticsStatusFromJSONTyped(json, false);
}

export function AnalyticsStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticsStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'popularPrefixQueries': json['popular_prefix_queries'] == null ? undefined : json['popular_prefix_queries'],
        'nohitsPrefixQueries': json['nohits_prefix_queries'] == null ? undefined : json['nohits_prefix_queries'],
        'logPrefixQueries': json['log_prefix_queries'] == null ? undefined : json['log_prefix_queries'],
        'queryLogEvents': json['query_log_events'] == null ? undefined : json['query_log_events'],
        'queryCounterEvents': json['query_counter_events'] == null ? undefined : json['query_counter_events'],
        'docLogEvents': json['doc_log_events'] == null ? undefined : json['doc_log_events'],
        'docCounterEvents': json['doc_counter_events'] == null ? undefined : json['doc_counter_events'],
    };
}

export function AnalyticsStatusToJSON(json: any): AnalyticsStatus {
    return AnalyticsStatusToJSONTyped(json, false);
}

export function AnalyticsStatusToJSONTyped(value?: AnalyticsStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'popular_prefix_queries': value['popularPrefixQueries'],
        'nohits_prefix_queries': value['nohitsPrefixQueries'],
        'log_prefix_queries': value['logPrefixQueries'],
        'query_log_events': value['queryLogEvents'],
        'query_counter_events': value['queryCounterEvents'],
        'doc_log_events': value['docLogEvents'],
        'doc_counter_events': value['docCounterEvents'],
    };
}

