/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeySchema
 */
export interface ApiKeySchema {
    /**
     * 
     * @type {string}
     * @memberof ApiKeySchema
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeySchema
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiKeySchema
     */
    actions: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiKeySchema
     */
    collections: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ApiKeySchema
     */
    expiresAt?: number;
}

/**
 * Check if a given object implements the ApiKeySchema interface.
 */
export function instanceOfApiKeySchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "actions" in value;
    isInstance = isInstance && "collections" in value;

    return isInstance;
}

export function ApiKeySchemaFromJSON(json: any): ApiKeySchema {
    return ApiKeySchemaFromJSONTyped(json, false);
}

export function ApiKeySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeySchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'description': json['description'],
        'actions': json['actions'],
        'collections': json['collections'],
        'expiresAt': !exists(json, 'expires_at') ? undefined : json['expires_at'],
    };
}

export function ApiKeySchemaToJSON(value?: ApiKeySchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'description': value.description,
        'actions': value.actions,
        'collections': value.collections,
        'expires_at': value.expiresAt,
    };
}

