/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyDeleteResponse
 */
export interface ApiKeyDeleteResponse {
    /**
     * The id of the API key that was deleted
     * @type {number}
     * @memberof ApiKeyDeleteResponse
     */
    id: number;
}

/**
 * Check if a given object implements the ApiKeyDeleteResponse interface.
 */
export function instanceOfApiKeyDeleteResponse(value: object): value is ApiKeyDeleteResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ApiKeyDeleteResponseFromJSON(json: any): ApiKeyDeleteResponse {
    return ApiKeyDeleteResponseFromJSONTyped(json, false);
}

export function ApiKeyDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ApiKeyDeleteResponseToJSON(json: any): ApiKeyDeleteResponse {
    return ApiKeyDeleteResponseToJSONTyped(json, false);
}

export function ApiKeyDeleteResponseToJSONTyped(value?: ApiKeyDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

