/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface APIStatsResponse
 */
export interface APIStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    deleteLatencyMs?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    deleteRequestsPerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    importLatencyMs?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    importRequestsPerSecond?: number;
    /**
     * 
     * @type {object}
     * @memberof APIStatsResponse
     */
    latencyMs?: object;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    overloadedRequestsPerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    pendingWriteBatches?: number;
    /**
     * 
     * @type {object}
     * @memberof APIStatsResponse
     */
    requestsPerSecond?: object;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    searchLatencyMs?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    searchRequestsPerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    totalRequestsPerSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    writeLatencyMs?: number;
    /**
     * 
     * @type {number}
     * @memberof APIStatsResponse
     */
    writeRequestsPerSecond?: number;
}

/**
 * Check if a given object implements the APIStatsResponse interface.
 */
export function instanceOfAPIStatsResponse(value: object): value is APIStatsResponse {
    return true;
}

export function APIStatsResponseFromJSON(json: any): APIStatsResponse {
    return APIStatsResponseFromJSONTyped(json, false);
}

export function APIStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): APIStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deleteLatencyMs': json['delete_latency_ms'] == null ? undefined : json['delete_latency_ms'],
        'deleteRequestsPerSecond': json['delete_requests_per_second'] == null ? undefined : json['delete_requests_per_second'],
        'importLatencyMs': json['import_latency_ms'] == null ? undefined : json['import_latency_ms'],
        'importRequestsPerSecond': json['import_requests_per_second'] == null ? undefined : json['import_requests_per_second'],
        'latencyMs': json['latency_ms'] == null ? undefined : json['latency_ms'],
        'overloadedRequestsPerSecond': json['overloaded_requests_per_second'] == null ? undefined : json['overloaded_requests_per_second'],
        'pendingWriteBatches': json['pending_write_batches'] == null ? undefined : json['pending_write_batches'],
        'requestsPerSecond': json['requests_per_second'] == null ? undefined : json['requests_per_second'],
        'searchLatencyMs': json['search_latency_ms'] == null ? undefined : json['search_latency_ms'],
        'searchRequestsPerSecond': json['search_requests_per_second'] == null ? undefined : json['search_requests_per_second'],
        'totalRequestsPerSecond': json['total_requests_per_second'] == null ? undefined : json['total_requests_per_second'],
        'writeLatencyMs': json['write_latency_ms'] == null ? undefined : json['write_latency_ms'],
        'writeRequestsPerSecond': json['write_requests_per_second'] == null ? undefined : json['write_requests_per_second'],
    };
}

export function APIStatsResponseToJSON(json: any): APIStatsResponse {
    return APIStatsResponseToJSONTyped(json, false);
}

export function APIStatsResponseToJSONTyped(value?: APIStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delete_latency_ms': value['deleteLatencyMs'],
        'delete_requests_per_second': value['deleteRequestsPerSecond'],
        'import_latency_ms': value['importLatencyMs'],
        'import_requests_per_second': value['importRequestsPerSecond'],
        'latency_ms': value['latencyMs'],
        'overloaded_requests_per_second': value['overloadedRequestsPerSecond'],
        'pending_write_batches': value['pendingWriteBatches'],
        'requests_per_second': value['requestsPerSecond'],
        'search_latency_ms': value['searchLatencyMs'],
        'search_requests_per_second': value['searchRequestsPerSecond'],
        'total_requests_per_second': value['totalRequestsPerSecond'],
        'write_latency_ms': value['writeLatencyMs'],
        'write_requests_per_second': value['writeRequestsPerSecond'],
    };
}

