/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Field } from './Field';
import {
    FieldFromJSON,
    FieldFromJSONTyped,
    FieldToJSON,
    FieldToJSONTyped,
} from './Field';

/**
 * 
 * @export
 * @interface CollectionUpdateSchema
 */
export interface CollectionUpdateSchema {
    /**
     * A list of fields for querying, filtering and faceting
     * @type {Array<Field>}
     * @memberof CollectionUpdateSchema
     */
    fields: Array<Field>;
    /**
     * List of synonym set names to associate with this collection
     * @type {Array<string>}
     * @memberof CollectionUpdateSchema
     */
    synonymSets?: Array<string>;
    /**
     * Optional details about the collection, e.g., when it was created, who created it etc.
     * 
     * @type {object}
     * @memberof CollectionUpdateSchema
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CollectionUpdateSchema interface.
 */
export function instanceOfCollectionUpdateSchema(value: object): value is CollectionUpdateSchema {
    if (!('fields' in value) || value['fields'] === undefined) return false;
    return true;
}

export function CollectionUpdateSchemaFromJSON(json: any): CollectionUpdateSchema {
    return CollectionUpdateSchemaFromJSONTyped(json, false);
}

export function CollectionUpdateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionUpdateSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'fields': ((json['fields'] as Array<any>).map(FieldFromJSON)),
        'synonymSets': json['synonym_sets'] == null ? undefined : json['synonym_sets'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CollectionUpdateSchemaToJSON(json: any): CollectionUpdateSchema {
    return CollectionUpdateSchemaToJSONTyped(json, false);
}

export function CollectionUpdateSchemaToJSONTyped(value?: CollectionUpdateSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fields': ((value['fields'] as Array<any>).map(FieldToJSON)),
        'synonym_sets': value['synonymSets'],
        'metadata': value['metadata'],
    };
}

