/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionResponseAllOf
 */
export interface CollectionResponseAllOf {
    /**
     * Number of documents in the collection
     * @type {number}
     * @memberof CollectionResponseAllOf
     */
    readonly numDocuments: number;
    /**
     * Timestamp of when the collection was created (Unix epoch in seconds)
     * @type {number}
     * @memberof CollectionResponseAllOf
     */
    readonly createdAt: number;
}

/**
 * Check if a given object implements the CollectionResponseAllOf interface.
 */
export function instanceOfCollectionResponseAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "numDocuments" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function CollectionResponseAllOfFromJSON(json: any): CollectionResponseAllOf {
    return CollectionResponseAllOfFromJSONTyped(json, false);
}

export function CollectionResponseAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionResponseAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'numDocuments': json['num_documents'],
        'createdAt': json['created_at'],
    };
}

export function CollectionResponseAllOfToJSON(value?: CollectionResponseAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

