/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionAlias
 */
export interface CollectionAlias {
    /**
     * Name of the collection alias
     * @type {string}
     * @memberof CollectionAlias
     */
    readonly name: string;
    /**
     * Name of the collection the alias mapped to
     * @type {string}
     * @memberof CollectionAlias
     */
    collectionName: string;
}

/**
 * Check if a given object implements the CollectionAlias interface.
 */
export function instanceOfCollectionAlias(value: object): value is CollectionAlias {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('collectionName' in value) || value['collectionName'] === undefined) return false;
    return true;
}

export function CollectionAliasFromJSON(json: any): CollectionAlias {
    return CollectionAliasFromJSONTyped(json, false);
}

export function CollectionAliasFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionAlias {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'collectionName': json['collection_name'],
    };
}

export function CollectionAliasToJSON(json: any): CollectionAlias {
    return CollectionAliasToJSONTyped(json, false);
}

export function CollectionAliasToJSONTyped(value?: Omit<CollectionAlias, 'name'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection_name': value['collectionName'],
    };
}

