/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Field } from './Field';
import {
    FieldFromJSON,
    FieldFromJSONTyped,
    FieldToJSON,
    FieldToJSONTyped,
} from './Field';
import type { VoiceQueryModelCollectionConfig } from './VoiceQueryModelCollectionConfig';
import {
    VoiceQueryModelCollectionConfigFromJSON,
    VoiceQueryModelCollectionConfigFromJSONTyped,
    VoiceQueryModelCollectionConfigToJSON,
    VoiceQueryModelCollectionConfigToJSONTyped,
} from './VoiceQueryModelCollectionConfig';

/**
 * 
 * @export
 * @interface CollectionResponse
 */
export interface CollectionResponse {
    /**
     * Name of the collection
     * @type {string}
     * @memberof CollectionResponse
     */
    name: string;
    /**
     * A list of fields for querying, filtering and faceting
     * @type {Array<Field>}
     * @memberof CollectionResponse
     */
    fields: Array<Field>;
    /**
     * The name of an int32 / float field that determines the order in which the search results are ranked when a sort_by clause is not provided during searching. This field must indicate some kind of popularity.
     * @type {string}
     * @memberof CollectionResponse
     */
    defaultSortingField?: string;
    /**
     * List of symbols or special characters to be used for splitting the text into individual words in addition to space and new-line characters.
     * 
     * @type {Array<string>}
     * @memberof CollectionResponse
     */
    tokenSeparators?: Array<string>;
    /**
     * List of synonym set names to associate with this collection
     * @type {Array<string>}
     * @memberof CollectionResponse
     */
    synonymSets?: Array<string>;
    /**
     * Enables experimental support at a collection level for nested object or object array fields. This field is only available if the Typesense server is version `0.24.0.rcn34` or later.
     * @type {boolean}
     * @memberof CollectionResponse
     */
    enableNestedFields?: boolean;
    /**
     * List of symbols or special characters to be indexed.
     * 
     * @type {Array<string>}
     * @memberof CollectionResponse
     */
    symbolsToIndex?: Array<string>;
    /**
     * 
     * @type {VoiceQueryModelCollectionConfig}
     * @memberof CollectionResponse
     */
    voiceQueryModel?: VoiceQueryModelCollectionConfig;
    /**
     * Optional details about the collection, e.g., when it was created, who created it etc.
     * 
     * @type {object}
     * @memberof CollectionResponse
     */
    metadata?: object;
    /**
     * Number of documents in the collection
     * @type {number}
     * @memberof CollectionResponse
     */
    readonly numDocuments: number;
    /**
     * Timestamp of when the collection was created (Unix epoch in seconds)
     * @type {number}
     * @memberof CollectionResponse
     */
    readonly createdAt: number;
}

/**
 * Check if a given object implements the CollectionResponse interface.
 */
export function instanceOfCollectionResponse(value: object): value is CollectionResponse {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('numDocuments' in value) || value['numDocuments'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CollectionResponseFromJSON(json: any): CollectionResponse {
    return CollectionResponseFromJSONTyped(json, false);
}

export function CollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'fields': ((json['fields'] as Array<any>).map(FieldFromJSON)),
        'defaultSortingField': json['default_sorting_field'] == null ? undefined : json['default_sorting_field'],
        'tokenSeparators': json['token_separators'] == null ? undefined : json['token_separators'],
        'synonymSets': json['synonym_sets'] == null ? undefined : json['synonym_sets'],
        'enableNestedFields': json['enable_nested_fields'] == null ? undefined : json['enable_nested_fields'],
        'symbolsToIndex': json['symbols_to_index'] == null ? undefined : json['symbols_to_index'],
        'voiceQueryModel': json['voice_query_model'] == null ? undefined : VoiceQueryModelCollectionConfigFromJSON(json['voice_query_model']),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'numDocuments': json['num_documents'],
        'createdAt': json['created_at'],
    };
}

export function CollectionResponseToJSON(json: any): CollectionResponse {
    return CollectionResponseToJSONTyped(json, false);
}

export function CollectionResponseToJSONTyped(value?: Omit<CollectionResponse, 'num_documents'|'created_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'fields': ((value['fields'] as Array<any>).map(FieldToJSON)),
        'default_sorting_field': value['defaultSortingField'],
        'token_separators': value['tokenSeparators'],
        'synonym_sets': value['synonymSets'],
        'enable_nested_fields': value['enableNestedFields'],
        'symbols_to_index': value['symbolsToIndex'],
        'voice_query_model': VoiceQueryModelCollectionConfigToJSON(value['voiceQueryModel']),
        'metadata': value['metadata'],
    };
}

