/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationModelCreateSchema
 */
export interface ConversationModelCreateSchema {
    /**
     * An explicit id for the model, otherwise the API will return a response with an auto-generated conversation model id.
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    id?: string;
    /**
     * Name of the LLM model offered by OpenAI, Cloudflare or vLLM
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    modelName: string;
    /**
     * The LLM service's API Key
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    apiKey?: string;
    /**
     * Typesense collection that stores the historical conversations
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    historyCollection: string;
    /**
     * LLM service's account ID (only applicable for Cloudflare)
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    accountId?: string;
    /**
     * The system prompt that contains special instructions to the LLM
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    systemPrompt?: string;
    /**
     * Time interval in seconds after which the messages would be deleted. Default: 86400 (24 hours)
     * 
     * @type {number}
     * @memberof ConversationModelCreateSchema
     */
    ttl?: number;
    /**
     * The maximum number of bytes to send to the LLM in every API call. Consult the LLM's documentation on the number of bytes supported in the context window.
     * 
     * @type {number}
     * @memberof ConversationModelCreateSchema
     */
    maxBytes: number;
    /**
     * URL of vLLM service
     * @type {string}
     * @memberof ConversationModelCreateSchema
     */
    vllmUrl?: string;
}

/**
 * Check if a given object implements the ConversationModelCreateSchema interface.
 */
export function instanceOfConversationModelCreateSchema(value: object): value is ConversationModelCreateSchema {
    if (!('modelName' in value) || value['modelName'] === undefined) return false;
    if (!('historyCollection' in value) || value['historyCollection'] === undefined) return false;
    if (!('maxBytes' in value) || value['maxBytes'] === undefined) return false;
    return true;
}

export function ConversationModelCreateSchemaFromJSON(json: any): ConversationModelCreateSchema {
    return ConversationModelCreateSchemaFromJSONTyped(json, false);
}

export function ConversationModelCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationModelCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'modelName': json['model_name'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'historyCollection': json['history_collection'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
        'systemPrompt': json['system_prompt'] == null ? undefined : json['system_prompt'],
        'ttl': json['ttl'] == null ? undefined : json['ttl'],
        'maxBytes': json['max_bytes'],
        'vllmUrl': json['vllm_url'] == null ? undefined : json['vllm_url'],
    };
}

export function ConversationModelCreateSchemaToJSON(json: any): ConversationModelCreateSchema {
    return ConversationModelCreateSchemaToJSONTyped(json, false);
}

export function ConversationModelCreateSchemaToJSONTyped(value?: ConversationModelCreateSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'model_name': value['modelName'],
        'api_key': value['apiKey'],
        'history_collection': value['historyCollection'],
        'account_id': value['accountId'],
        'system_prompt': value['systemPrompt'],
        'ttl': value['ttl'],
        'max_bytes': value['maxBytes'],
        'vllm_url': value['vllmUrl'],
    };
}

