/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AnalyticsRule } from './AnalyticsRule';
import {
    instanceOfAnalyticsRule,
    AnalyticsRuleFromJSON,
    AnalyticsRuleFromJSONTyped,
    AnalyticsRuleToJSON,
} from './AnalyticsRule';
import type { CreateAnalyticsRule200ResponseOneOfInnerOneOf } from './CreateAnalyticsRule200ResponseOneOfInnerOneOf';
import {
    instanceOfCreateAnalyticsRule200ResponseOneOfInnerOneOf,
    CreateAnalyticsRule200ResponseOneOfInnerOneOfFromJSON,
    CreateAnalyticsRule200ResponseOneOfInnerOneOfFromJSONTyped,
    CreateAnalyticsRule200ResponseOneOfInnerOneOfToJSON,
} from './CreateAnalyticsRule200ResponseOneOfInnerOneOf';

/**
 * @type CreateAnalyticsRule200ResponseOneOfInner
 *
 * @export
 */
export type CreateAnalyticsRule200ResponseOneOfInner = AnalyticsRule | CreateAnalyticsRule200ResponseOneOfInnerOneOf;

/**
 * Check if a given object implements the CreateAnalyticsRule200ResponseOneOfInner interface.
 */
export function instanceOfCreateAnalyticsRule200ResponseOneOfInner(value: object): value is CreateAnalyticsRule200ResponseOneOfInner {
    return instanceOfAnalyticsRule(value) || instanceOfCreateAnalyticsRule200ResponseOneOfInnerOneOf(value);
}

export function CreateAnalyticsRule200ResponseOneOfInnerFromJSON(json: any): CreateAnalyticsRule200ResponseOneOfInner {
    return CreateAnalyticsRule200ResponseOneOfInnerFromJSONTyped(json, false);
}

export function CreateAnalyticsRule200ResponseOneOfInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalyticsRule200ResponseOneOfInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAnalyticsRule(json)) {
        return AnalyticsRuleFromJSONTyped(json, true);
    }
    if (instanceOfCreateAnalyticsRule200ResponseOneOfInnerOneOf(json)) {
        return CreateAnalyticsRule200ResponseOneOfInnerOneOfFromJSONTyped(json, true);
    }
    return {} as any;
}

export function CreateAnalyticsRule200ResponseOneOfInnerToJSON(json: any): any {
    return CreateAnalyticsRule200ResponseOneOfInnerToJSONTyped(json, false);
}

export function CreateAnalyticsRule200ResponseOneOfInnerToJSONTyped(value?: CreateAnalyticsRule200ResponseOneOfInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAnalyticsRule(value)) {
        return AnalyticsRuleToJSON(value as AnalyticsRule);
    }
    if (instanceOfCreateAnalyticsRule200ResponseOneOfInnerOneOf(value)) {
        return CreateAnalyticsRule200ResponseOneOfInnerOneOfToJSON(value as CreateAnalyticsRule200ResponseOneOfInnerOneOf);
    }
    return {};
}

