/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateAnalyticsRule200ResponseOneOfInner } from './CreateAnalyticsRule200ResponseOneOfInner';
import {
    instanceOfCreateAnalyticsRule200ResponseOneOfInner,
    CreateAnalyticsRule200ResponseOneOfInnerFromJSON,
    CreateAnalyticsRule200ResponseOneOfInnerFromJSONTyped,
    CreateAnalyticsRule200ResponseOneOfInnerToJSON,
} from './CreateAnalyticsRule200ResponseOneOfInner';
import type { AnalyticsRule } from './AnalyticsRule';
import {
    instanceOfAnalyticsRule,
    AnalyticsRuleFromJSON,
    AnalyticsRuleFromJSONTyped,
    AnalyticsRuleToJSON,
} from './AnalyticsRule';

/**
 * @type CreateAnalyticsRule200Response
 * 
 * @export
 */
export type CreateAnalyticsRule200Response = AnalyticsRule | Array<CreateAnalyticsRule200ResponseOneOfInner>;

export function CreateAnalyticsRule200ResponseFromJSON(json: any): CreateAnalyticsRule200Response {
    return CreateAnalyticsRule200ResponseFromJSONTyped(json, false);
}

export function CreateAnalyticsRule200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalyticsRule200Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAnalyticsRule(json)) {
        return AnalyticsRuleFromJSONTyped(json, true);
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfCreateAnalyticsRule200ResponseOneOfInner(item))) {
                return json.map(value => CreateAnalyticsRule200ResponseOneOfInnerFromJSONTyped(value, true));
            }
        }
        return json;
    }
    return {} as any;
}

export function CreateAnalyticsRule200ResponseToJSON(json: any): any {
    return CreateAnalyticsRule200ResponseToJSONTyped(json, false);
}

export function CreateAnalyticsRule200ResponseToJSONTyped(value?: CreateAnalyticsRule200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAnalyticsRule(value)) {
        return AnalyticsRuleToJSON(value as AnalyticsRule);
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfCreateAnalyticsRule200ResponseOneOfInner(item))) {
                return value.map(value => CreateAnalyticsRule200ResponseOneOfInnerToJSON(value as CreateAnalyticsRule200ResponseOneOfInner));
            }
        }
        return value;
    }
    return {};
}

