/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAnalyticsRule200ResponseOneOfInnerOneOf
 */
export interface CreateAnalyticsRule200ResponseOneOfInnerOneOf {
    /**
     * 
     * @type {string}
     * @memberof CreateAnalyticsRule200ResponseOneOfInnerOneOf
     */
    error?: string;
}

/**
 * Check if a given object implements the CreateAnalyticsRule200ResponseOneOfInnerOneOf interface.
 */
export function instanceOfCreateAnalyticsRule200ResponseOneOfInnerOneOf(value: object): value is CreateAnalyticsRule200ResponseOneOfInnerOneOf {
    return true;
}

export function CreateAnalyticsRule200ResponseOneOfInnerOneOfFromJSON(json: any): CreateAnalyticsRule200ResponseOneOfInnerOneOf {
    return CreateAnalyticsRule200ResponseOneOfInnerOneOfFromJSONTyped(json, false);
}

export function CreateAnalyticsRule200ResponseOneOfInnerOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalyticsRule200ResponseOneOfInnerOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CreateAnalyticsRule200ResponseOneOfInnerOneOfToJSON(json: any): CreateAnalyticsRule200ResponseOneOfInnerOneOf {
    return CreateAnalyticsRule200ResponseOneOfInnerOneOfToJSONTyped(json, false);
}

export function CreateAnalyticsRule200ResponseOneOfInnerOneOfToJSONTyped(value?: CreateAnalyticsRule200ResponseOneOfInnerOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

