/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AnalyticsRuleCreate } from './AnalyticsRuleCreate';
import {
    instanceOfAnalyticsRuleCreate,
    AnalyticsRuleCreateFromJSON,
    AnalyticsRuleCreateFromJSONTyped,
    AnalyticsRuleCreateToJSON,
} from './AnalyticsRuleCreate';
import type { AnalyticsRuleCreate } from './AnalyticsRuleCreate';
import {
    instanceOfAnalyticsRuleCreate,
    AnalyticsRuleCreateFromJSON,
    AnalyticsRuleCreateFromJSONTyped,
    AnalyticsRuleCreateToJSON,
} from './AnalyticsRuleCreate';

/**
 * @type CreateAnalyticsRuleRequest
 * 
 * @export
 */
export type CreateAnalyticsRuleRequest = AnalyticsRuleCreate | Array<AnalyticsRuleCreate>;

export function CreateAnalyticsRuleRequestFromJSON(json: any): CreateAnalyticsRuleRequest {
    return CreateAnalyticsRuleRequestFromJSONTyped(json, false);
}

export function CreateAnalyticsRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAnalyticsRuleRequest {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfAnalyticsRuleCreate(json)) {
        return AnalyticsRuleCreateFromJSONTyped(json, true);
    }
    if (Array.isArray(json)) {
        if (json.every(item => typeof item === 'object')) {
            if (json.every(item => instanceOfAnalyticsRuleCreate(item))) {
                return json.map(value => AnalyticsRuleCreateFromJSONTyped(value, true));
            }
        }
        return json;
    }
    return {} as any;
}

export function CreateAnalyticsRuleRequestToJSON(json: any): any {
    return CreateAnalyticsRuleRequestToJSONTyped(json, false);
}

export function CreateAnalyticsRuleRequestToJSONTyped(value?: CreateAnalyticsRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfAnalyticsRuleCreate(value)) {
        return AnalyticsRuleCreateToJSON(value as AnalyticsRuleCreate);
    }
    if (Array.isArray(value)) {
        if (value.every(item => typeof item === 'object')) {
            if (value.every(item => instanceOfAnalyticsRuleCreate(item))) {
                return value.map(value => AnalyticsRuleCreateToJSON(value as AnalyticsRuleCreate));
            }
        }
        return value;
    }
    return {};
}

