/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurationSetDeleteSchema
 */
export interface CurationSetDeleteSchema {
    /**
     * Name of the deleted curation set
     * @type {string}
     * @memberof CurationSetDeleteSchema
     */
    name: string;
}

/**
 * Check if a given object implements the CurationSetDeleteSchema interface.
 */
export function instanceOfCurationSetDeleteSchema(value: object): value is CurationSetDeleteSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CurationSetDeleteSchemaFromJSON(json: any): CurationSetDeleteSchema {
    return CurationSetDeleteSchemaFromJSONTyped(json, false);
}

export function CurationSetDeleteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurationSetDeleteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CurationSetDeleteSchemaToJSON(json: any): CurationSetDeleteSchema {
    return CurationSetDeleteSchemaToJSONTyped(json, false);
}

export function CurationSetDeleteSchemaToJSONTyped(value?: CurationSetDeleteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

