/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Debug200Response
 */
export interface Debug200Response {
    /**
     * 
     * @type {string}
     * @memberof Debug200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the Debug200Response interface.
 */
export function instanceOfDebug200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function Debug200ResponseFromJSON(json: any): Debug200Response {
    return Debug200ResponseFromJSONTyped(json, false);
}

export function Debug200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Debug200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function Debug200ResponseToJSON(value?: Debug200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
    };
}

