/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Debug200Response
 */
export interface Debug200Response {
    /**
     * 
     * @type {string}
     * @memberof Debug200Response
     */
    version?: string;
}

/**
 * Check if a given object implements the Debug200Response interface.
 */
export function instanceOfDebug200Response(value: object): value is Debug200Response {
    return true;
}

export function Debug200ResponseFromJSON(json: any): Debug200Response {
    return Debug200ResponseFromJSONTyped(json, false);
}

export function Debug200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Debug200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function Debug200ResponseToJSON(json: any): Debug200Response {
    return Debug200ResponseToJSONTyped(json, false);
}

export function Debug200ResponseToJSONTyped(value?: Debug200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
    };
}

