/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteDocumentsDeleteDocumentsParametersParameter
 */
export interface DeleteDocumentsDeleteDocumentsParametersParameter {
    /**
     * 
     * @type {string}
     * @memberof DeleteDocumentsDeleteDocumentsParametersParameter
     */
    filterBy: string;
    /**
     * Batch size parameter controls the number of documents that should be deleted at a time. A larger value will speed up deletions, but will impact performance of other operations running on the server.
     * @type {number}
     * @memberof DeleteDocumentsDeleteDocumentsParametersParameter
     */
    batchSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteDocumentsDeleteDocumentsParametersParameter
     */
    ignoreNotFound?: boolean;
    /**
     * When true, removes all documents from the collection while preserving the collection and its schema.
     * @type {boolean}
     * @memberof DeleteDocumentsDeleteDocumentsParametersParameter
     */
    truncate?: boolean;
}

/**
 * Check if a given object implements the DeleteDocumentsDeleteDocumentsParametersParameter interface.
 */
export function instanceOfDeleteDocumentsDeleteDocumentsParametersParameter(value: object): value is DeleteDocumentsDeleteDocumentsParametersParameter {
    if (!('filterBy' in value) || value['filterBy'] === undefined) return false;
    return true;
}

export function DeleteDocumentsDeleteDocumentsParametersParameterFromJSON(json: any): DeleteDocumentsDeleteDocumentsParametersParameter {
    return DeleteDocumentsDeleteDocumentsParametersParameterFromJSONTyped(json, false);
}

export function DeleteDocumentsDeleteDocumentsParametersParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteDocumentsDeleteDocumentsParametersParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'filterBy': json['filter_by'],
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
        'ignoreNotFound': json['ignore_not_found'] == null ? undefined : json['ignore_not_found'],
        'truncate': json['truncate'] == null ? undefined : json['truncate'],
    };
}

export function DeleteDocumentsDeleteDocumentsParametersParameterToJSON(json: any): DeleteDocumentsDeleteDocumentsParametersParameter {
    return DeleteDocumentsDeleteDocumentsParametersParameterToJSONTyped(json, false);
}

export function DeleteDocumentsDeleteDocumentsParametersParameterToJSONTyped(value?: DeleteDocumentsDeleteDocumentsParametersParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter_by': value['filterBy'],
        'batch_size': value['batchSize'],
        'ignore_not_found': value['ignoreNotFound'],
        'truncate': value['truncate'],
    };
}

