/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DirtyValues = {
    CoerceOrReject: 'coerce_or_reject',
    CoerceOrDrop: 'coerce_or_drop',
    Drop: 'drop',
    Reject: 'reject'
} as const;
export type DirtyValues = typeof DirtyValues[keyof typeof DirtyValues];


export function instanceOfDirtyValues(value: any): boolean {
    for (const key in DirtyValues) {
        if (Object.prototype.hasOwnProperty.call(DirtyValues, key)) {
            if (DirtyValues[key as keyof typeof DirtyValues] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DirtyValuesFromJSON(json: any): DirtyValues {
    return DirtyValuesFromJSONTyped(json, false);
}

export function DirtyValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirtyValues {
    return json as DirtyValues;
}

export function DirtyValuesToJSON(value?: DirtyValues | null): any {
    return value as any;
}

export function DirtyValuesToJSONTyped(value: any, ignoreDiscriminator: boolean): DirtyValues {
    return value as DirtyValues;
}

