/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Dictates the direction in which the words in the query must be dropped when the original words in the query do not appear in any document. Values: right_to_left (default), left_to_right, both_sides:3 A note on both_sides:3 - for queries up to 3 tokens (words) in length, this mode will drop tokens from both sides and exhaustively rank all matching results. If query length is greater than 3 words, Typesense will just fallback to default behavior of right_to_left
 * 
 * @export
 */
export const DropTokensMode = {
    RightToLeft: 'right_to_left',
    LeftToRight: 'left_to_right',
    BothSides3: 'both_sides:3'
} as const;
export type DropTokensMode = typeof DropTokensMode[keyof typeof DropTokensMode];


export function instanceOfDropTokensMode(value: any): boolean {
    for (const key in DropTokensMode) {
        if (Object.prototype.hasOwnProperty.call(DropTokensMode, key)) {
            if (DropTokensMode[key as keyof typeof DropTokensMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DropTokensModeFromJSON(json: any): DropTokensMode {
    return DropTokensModeFromJSONTyped(json, false);
}

export function DropTokensModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DropTokensMode {
    return json as DropTokensMode;
}

export function DropTokensModeToJSON(value?: DropTokensMode | null): any {
    return value as any;
}

export function DropTokensModeToJSONTyped(value: any, ignoreDiscriminator: boolean): DropTokensMode {
    return value as DropTokensMode;
}

