/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportDocumentsExportDocumentsParametersParameter
 */
export interface ExportDocumentsExportDocumentsParametersParameter {
    /**
     * Filter conditions for refining your search results. Separate multiple conditions with &&.
     * @type {string}
     * @memberof ExportDocumentsExportDocumentsParametersParameter
     */
    filterBy?: string;
    /**
     * List of fields from the document to include in the search result
     * @type {string}
     * @memberof ExportDocumentsExportDocumentsParametersParameter
     */
    includeFields?: string;
    /**
     * List of fields from the document to exclude in the search result
     * @type {string}
     * @memberof ExportDocumentsExportDocumentsParametersParameter
     */
    excludeFields?: string;
}

/**
 * Check if a given object implements the ExportDocumentsExportDocumentsParametersParameter interface.
 */
export function instanceOfExportDocumentsExportDocumentsParametersParameter(value: object): value is ExportDocumentsExportDocumentsParametersParameter {
    return true;
}

export function ExportDocumentsExportDocumentsParametersParameterFromJSON(json: any): ExportDocumentsExportDocumentsParametersParameter {
    return ExportDocumentsExportDocumentsParametersParameterFromJSONTyped(json, false);
}

export function ExportDocumentsExportDocumentsParametersParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportDocumentsExportDocumentsParametersParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'filterBy': json['filter_by'] == null ? undefined : json['filter_by'],
        'includeFields': json['include_fields'] == null ? undefined : json['include_fields'],
        'excludeFields': json['exclude_fields'] == null ? undefined : json['exclude_fields'],
    };
}

export function ExportDocumentsExportDocumentsParametersParameterToJSON(json: any): ExportDocumentsExportDocumentsParametersParameter {
    return ExportDocumentsExportDocumentsParametersParameterToJSONTyped(json, false);
}

export function ExportDocumentsExportDocumentsParametersParameterToJSONTyped(value?: ExportDocumentsExportDocumentsParametersParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter_by': value['filterBy'],
        'include_fields': value['includeFields'],
        'exclude_fields': value['excludeFields'],
    };
}

