/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacetCountsCountsInner
 */
export interface FacetCountsCountsInner {
    /**
     * 
     * @type {number}
     * @memberof FacetCountsCountsInner
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof FacetCountsCountsInner
     */
    highlighted?: string;
    /**
     * 
     * @type {string}
     * @memberof FacetCountsCountsInner
     */
    value?: string;
}

/**
 * Check if a given object implements the FacetCountsCountsInner interface.
 */
export function instanceOfFacetCountsCountsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FacetCountsCountsInnerFromJSON(json: any): FacetCountsCountsInner {
    return FacetCountsCountsInnerFromJSONTyped(json, false);
}

export function FacetCountsCountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacetCountsCountsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'highlighted': !exists(json, 'highlighted') ? undefined : json['highlighted'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function FacetCountsCountsInnerToJSON(value?: FacetCountsCountsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'highlighted': value.highlighted,
        'value': value.value,
    };
}

