/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FacetCountsCountsInner
 */
export interface FacetCountsCountsInner {
    /**
     * 
     * @type {number}
     * @memberof FacetCountsCountsInner
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof FacetCountsCountsInner
     */
    highlighted?: string;
    /**
     * 
     * @type {string}
     * @memberof FacetCountsCountsInner
     */
    value?: string;
    /**
     * 
     * @type {object}
     * @memberof FacetCountsCountsInner
     */
    parent?: object;
}

/**
 * Check if a given object implements the FacetCountsCountsInner interface.
 */
export function instanceOfFacetCountsCountsInner(value: object): value is FacetCountsCountsInner {
    return true;
}

export function FacetCountsCountsInnerFromJSON(json: any): FacetCountsCountsInner {
    return FacetCountsCountsInnerFromJSONTyped(json, false);
}

export function FacetCountsCountsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FacetCountsCountsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'highlighted': json['highlighted'] == null ? undefined : json['highlighted'],
        'value': json['value'] == null ? undefined : json['value'],
        'parent': json['parent'] == null ? undefined : json['parent'],
    };
}

export function FacetCountsCountsInnerToJSON(json: any): FacetCountsCountsInner {
    return FacetCountsCountsInnerToJSONTyped(json, false);
}

export function FacetCountsCountsInnerToJSONTyped(value?: FacetCountsCountsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'highlighted': value['highlighted'],
        'value': value['value'],
        'parent': value['parent'],
    };
}

