/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldEmbedModelConfig
 */
export interface FieldEmbedModelConfig {
    /**
     * 
     * @type {string}
     * @memberof FieldEmbedModelConfig
     */
    modelName: string;
    /**
     * 
     * @type {string}
     * @memberof FieldEmbedModelConfig
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldEmbedModelConfig
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldEmbedModelConfig
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldEmbedModelConfig
     */
    clientSecret?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldEmbedModelConfig
     */
    projectId?: string;
}

/**
 * Check if a given object implements the FieldEmbedModelConfig interface.
 */
export function instanceOfFieldEmbedModelConfig(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "modelName" in value;

    return isInstance;
}

export function FieldEmbedModelConfigFromJSON(json: any): FieldEmbedModelConfig {
    return FieldEmbedModelConfigFromJSONTyped(json, false);
}

export function FieldEmbedModelConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldEmbedModelConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'modelName': json['model_name'],
        'apiKey': !exists(json, 'api_key') ? undefined : json['api_key'],
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'clientId': !exists(json, 'client_id') ? undefined : json['client_id'],
        'clientSecret': !exists(json, 'client_secret') ? undefined : json['client_secret'],
        'projectId': !exists(json, 'project_id') ? undefined : json['project_id'],
    };
}

export function FieldEmbedModelConfigToJSON(value?: FieldEmbedModelConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_name': value.modelName,
        'api_key': value.apiKey,
        'access_token': value.accessToken,
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
        'project_id': value.projectId,
    };
}

