/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FieldEmbed } from './FieldEmbed';
import {
    FieldEmbedFromJSON,
    FieldEmbedFromJSONTyped,
    FieldEmbedToJSON,
    FieldEmbedToJSONTyped,
} from './FieldEmbed';

/**
 * 
 * @export
 * @interface Field
 */
export interface Field {
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    optional?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    facet?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    index?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Field
     */
    locale?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    sort?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    infix?: boolean;
    /**
     * Name of a field in another collection that should be linked to this collection so that it can be joined during query.
     * 
     * @type {string}
     * @memberof Field
     */
    reference?: string;
    /**
     * Allow documents to be indexed successfully even when the referenced document doesn't exist yet.
     * 
     * @type {boolean}
     * @memberof Field
     */
    asyncReference?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Field
     */
    numDim?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Field
     */
    drop?: boolean;
    /**
     * When set to false, the field value will not be stored on disk. Default: true.
     * 
     * @type {boolean}
     * @memberof Field
     */
    store?: boolean;
    /**
     * The distance metric to be used for vector search. Default: `cosine`. You can also use `ip` for inner product.
     * 
     * @type {string}
     * @memberof Field
     */
    vecDist?: string;
    /**
     * Enables an index optimized for range filtering on numerical fields (e.g. rating:>3.5). Default: false.
     * 
     * @type {boolean}
     * @memberof Field
     */
    rangeIndex?: boolean;
    /**
     * Values are stemmed before indexing in-memory. Default: false.
     * 
     * @type {boolean}
     * @memberof Field
     */
    stem?: boolean;
    /**
     * Name of the stemming dictionary to use for this field
     * @type {string}
     * @memberof Field
     */
    stemDictionary?: string;
    /**
     * List of symbols or special characters to be used for splitting the text into individual words in addition to space and new-line characters.
     * 
     * @type {Array<string>}
     * @memberof Field
     */
    tokenSeparators?: Array<string>;
    /**
     * List of symbols or special characters to be indexed.
     * 
     * @type {Array<string>}
     * @memberof Field
     */
    symbolsToIndex?: Array<string>;
    /**
     * 
     * @type {FieldEmbed}
     * @memberof Field
     */
    embed?: FieldEmbed;
}

/**
 * Check if a given object implements the Field interface.
 */
export function instanceOfField(value: object): value is Field {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FieldFromJSON(json: any): Field {
    return FieldFromJSONTyped(json, false);
}

export function FieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): Field {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'optional': json['optional'] == null ? undefined : json['optional'],
        'facet': json['facet'] == null ? undefined : json['facet'],
        'index': json['index'] == null ? undefined : json['index'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'sort': json['sort'] == null ? undefined : json['sort'],
        'infix': json['infix'] == null ? undefined : json['infix'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'asyncReference': json['async_reference'] == null ? undefined : json['async_reference'],
        'numDim': json['num_dim'] == null ? undefined : json['num_dim'],
        'drop': json['drop'] == null ? undefined : json['drop'],
        'store': json['store'] == null ? undefined : json['store'],
        'vecDist': json['vec_dist'] == null ? undefined : json['vec_dist'],
        'rangeIndex': json['range_index'] == null ? undefined : json['range_index'],
        'stem': json['stem'] == null ? undefined : json['stem'],
        'stemDictionary': json['stem_dictionary'] == null ? undefined : json['stem_dictionary'],
        'tokenSeparators': json['token_separators'] == null ? undefined : json['token_separators'],
        'symbolsToIndex': json['symbols_to_index'] == null ? undefined : json['symbols_to_index'],
        'embed': json['embed'] == null ? undefined : FieldEmbedFromJSON(json['embed']),
    };
}

export function FieldToJSON(json: any): Field {
    return FieldToJSONTyped(json, false);
}

export function FieldToJSONTyped(value?: Field | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'type': value['type'],
        'optional': value['optional'],
        'facet': value['facet'],
        'index': value['index'],
        'locale': value['locale'],
        'sort': value['sort'],
        'infix': value['infix'],
        'reference': value['reference'],
        'async_reference': value['asyncReference'],
        'num_dim': value['numDim'],
        'drop': value['drop'],
        'store': value['store'],
        'vec_dist': value['vecDist'],
        'range_index': value['rangeIndex'],
        'stem': value['stem'],
        'stem_dictionary': value['stemDictionary'],
        'token_separators': value['tokenSeparators'],
        'symbols_to_index': value['symbolsToIndex'],
        'embed': FieldEmbedToJSON(value['embed']),
    };
}

