/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DirtyValues } from './DirtyValues';
import {
    DirtyValuesFromJSON,
    DirtyValuesFromJSONTyped,
    DirtyValuesToJSON,
    DirtyValuesToJSONTyped,
} from './DirtyValues';
import type { IndexAction } from './IndexAction';
import {
    IndexActionFromJSON,
    IndexActionFromJSONTyped,
    IndexActionToJSON,
    IndexActionToJSONTyped,
} from './IndexAction';

/**
 * 
 * @export
 * @interface ImportDocumentsImportDocumentsParametersParameter
 */
export interface ImportDocumentsImportDocumentsParametersParameter {
    /**
     * 
     * @type {number}
     * @memberof ImportDocumentsImportDocumentsParametersParameter
     */
    batchSize?: number;
    /**
     * Returning the id of the imported documents. If you want the import response to return the ingested document's id in the response, you can use the return_id parameter.
     * @type {boolean}
     * @memberof ImportDocumentsImportDocumentsParametersParameter
     */
    returnId?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ImportDocumentsImportDocumentsParametersParameter
     */
    remoteEmbeddingBatchSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ImportDocumentsImportDocumentsParametersParameter
     */
    returnDoc?: boolean;
    /**
     * 
     * @type {IndexAction}
     * @memberof ImportDocumentsImportDocumentsParametersParameter
     */
    action?: IndexAction;
    /**
     * 
     * @type {DirtyValues}
     * @memberof ImportDocumentsImportDocumentsParametersParameter
     */
    dirtyValues?: DirtyValues;
}



/**
 * Check if a given object implements the ImportDocumentsImportDocumentsParametersParameter interface.
 */
export function instanceOfImportDocumentsImportDocumentsParametersParameter(value: object): value is ImportDocumentsImportDocumentsParametersParameter {
    return true;
}

export function ImportDocumentsImportDocumentsParametersParameterFromJSON(json: any): ImportDocumentsImportDocumentsParametersParameter {
    return ImportDocumentsImportDocumentsParametersParameterFromJSONTyped(json, false);
}

export function ImportDocumentsImportDocumentsParametersParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportDocumentsImportDocumentsParametersParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'batchSize': json['batch_size'] == null ? undefined : json['batch_size'],
        'returnId': json['return_id'] == null ? undefined : json['return_id'],
        'remoteEmbeddingBatchSize': json['remote_embedding_batch_size'] == null ? undefined : json['remote_embedding_batch_size'],
        'returnDoc': json['return_doc'] == null ? undefined : json['return_doc'],
        'action': json['action'] == null ? undefined : IndexActionFromJSON(json['action']),
        'dirtyValues': json['dirty_values'] == null ? undefined : DirtyValuesFromJSON(json['dirty_values']),
    };
}

export function ImportDocumentsImportDocumentsParametersParameterToJSON(json: any): ImportDocumentsImportDocumentsParametersParameter {
    return ImportDocumentsImportDocumentsParametersParameterToJSONTyped(json, false);
}

export function ImportDocumentsImportDocumentsParametersParameterToJSONTyped(value?: ImportDocumentsImportDocumentsParametersParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'batch_size': value['batchSize'],
        'return_id': value['returnId'],
        'remote_embedding_batch_size': value['remoteEmbeddingBatchSize'],
        'return_doc': value['returnDoc'],
        'action': IndexActionToJSON(value['action']),
        'dirty_values': DirtyValuesToJSON(value['dirtyValues']),
    };
}

