/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IndexAction = {
    Create: 'create',
    Update: 'update',
    Upsert: 'upsert',
    Emplace: 'emplace'
} as const;
export type IndexAction = typeof IndexAction[keyof typeof IndexAction];


export function instanceOfIndexAction(value: any): boolean {
    for (const key in IndexAction) {
        if (Object.prototype.hasOwnProperty.call(IndexAction, key)) {
            if (IndexAction[key as keyof typeof IndexAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IndexActionFromJSON(json: any): IndexAction {
    return IndexActionFromJSONTyped(json, false);
}

export function IndexActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexAction {
    return json as IndexAction;
}

export function IndexActionToJSON(value?: IndexAction | null): any {
    return value as any;
}

export function IndexActionToJSONTyped(value: any, ignoreDiscriminator: boolean): IndexAction {
    return value as IndexAction;
}

