/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchResult } from './SearchResult';
import {
    SearchResultFromJSON,
    SearchResultFromJSONTyped,
    SearchResultToJSON,
} from './SearchResult';

/**
 * 
 * @export
 * @interface MultiSearchResult
 */
export interface MultiSearchResult {
    /**
     * 
     * @type {Array<SearchResult>}
     * @memberof MultiSearchResult
     */
    results: Array<SearchResult>;
}

/**
 * Check if a given object implements the MultiSearchResult interface.
 */
export function instanceOfMultiSearchResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "results" in value;

    return isInstance;
}

export function MultiSearchResultFromJSON(json: any): MultiSearchResult {
    return MultiSearchResultFromJSONTyped(json, false);
}

export function MultiSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiSearchResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(SearchResultFromJSON)),
    };
}

export function MultiSearchResultToJSON(value?: MultiSearchResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': ((value.results as Array<any>).map(SearchResultToJSON)),
    };
}

