/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiSearchResultItem } from './MultiSearchResultItem';
import {
    MultiSearchResultItemFromJSON,
    MultiSearchResultItemFromJSONTyped,
    MultiSearchResultItemToJSON,
    MultiSearchResultItemToJSONTyped,
} from './MultiSearchResultItem';
import type { SearchResultConversation } from './SearchResultConversation';
import {
    SearchResultConversationFromJSON,
    SearchResultConversationFromJSONTyped,
    SearchResultConversationToJSON,
    SearchResultConversationToJSONTyped,
} from './SearchResultConversation';

/**
 * 
 * @export
 * @interface MultiSearchResult
 */
export interface MultiSearchResult {
    /**
     * 
     * @type {Array<MultiSearchResultItem>}
     * @memberof MultiSearchResult
     */
    results: Array<MultiSearchResultItem>;
    /**
     * 
     * @type {SearchResultConversation}
     * @memberof MultiSearchResult
     */
    conversation?: SearchResultConversation;
}

/**
 * Check if a given object implements the MultiSearchResult interface.
 */
export function instanceOfMultiSearchResult(value: object): value is MultiSearchResult {
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function MultiSearchResultFromJSON(json: any): MultiSearchResult {
    return MultiSearchResultFromJSONTyped(json, false);
}

export function MultiSearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiSearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(MultiSearchResultItemFromJSON)),
        'conversation': json['conversation'] == null ? undefined : SearchResultConversationFromJSON(json['conversation']),
    };
}

export function MultiSearchResultToJSON(json: any): MultiSearchResult {
    return MultiSearchResultToJSONTyped(json, false);
}

export function MultiSearchResultToJSONTyped(value?: MultiSearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': ((value['results'] as Array<any>).map(MultiSearchResultItemToJSON)),
        'conversation': SearchResultConversationToJSON(value['conversation']),
    };
}

