/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NLSearchModelDeleteSchema
 */
export interface NLSearchModelDeleteSchema {
    /**
     * ID of the deleted NL search model
     * @type {string}
     * @memberof NLSearchModelDeleteSchema
     */
    id: string;
}

/**
 * Check if a given object implements the NLSearchModelDeleteSchema interface.
 */
export function instanceOfNLSearchModelDeleteSchema(value: object): value is NLSearchModelDeleteSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function NLSearchModelDeleteSchemaFromJSON(json: any): NLSearchModelDeleteSchema {
    return NLSearchModelDeleteSchemaFromJSONTyped(json, false);
}

export function NLSearchModelDeleteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NLSearchModelDeleteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function NLSearchModelDeleteSchemaToJSON(json: any): NLSearchModelDeleteSchema {
    return NLSearchModelDeleteSchemaToJSONTyped(json, false);
}

export function NLSearchModelDeleteSchemaToJSONTyped(value?: NLSearchModelDeleteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

