/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NLSearchModelBase
 */
export interface NLSearchModelBase {
    /**
     * Name of the NL model to use
     * @type {string}
     * @memberof NLSearchModelBase
     */
    modelName?: string;
    /**
     * API key for the NL model service
     * @type {string}
     * @memberof NLSearchModelBase
     */
    apiKey?: string;
    /**
     * Custom API URL for the NL model service
     * @type {string}
     * @memberof NLSearchModelBase
     */
    apiUrl?: string;
    /**
     * Maximum number of bytes to process
     * @type {number}
     * @memberof NLSearchModelBase
     */
    maxBytes?: number;
    /**
     * Temperature parameter for the NL model
     * @type {number}
     * @memberof NLSearchModelBase
     */
    temperature?: number;
    /**
     * System prompt for the NL model
     * @type {string}
     * @memberof NLSearchModelBase
     */
    systemPrompt?: string;
    /**
     * Top-p parameter for the NL model (Google-specific)
     * @type {number}
     * @memberof NLSearchModelBase
     */
    topP?: number;
    /**
     * Top-k parameter for the NL model (Google-specific)
     * @type {number}
     * @memberof NLSearchModelBase
     */
    topK?: number;
    /**
     * Stop sequences for the NL model (Google-specific)
     * @type {Array<string>}
     * @memberof NLSearchModelBase
     */
    stopSequences?: Array<string>;
    /**
     * API version for the NL model service
     * @type {string}
     * @memberof NLSearchModelBase
     */
    apiVersion?: string;
    /**
     * Project ID for GCP Vertex AI
     * @type {string}
     * @memberof NLSearchModelBase
     */
    projectId?: string;
    /**
     * Access token for GCP Vertex AI
     * @type {string}
     * @memberof NLSearchModelBase
     */
    accessToken?: string;
    /**
     * Refresh token for GCP Vertex AI
     * @type {string}
     * @memberof NLSearchModelBase
     */
    refreshToken?: string;
    /**
     * Client ID for GCP Vertex AI
     * @type {string}
     * @memberof NLSearchModelBase
     */
    clientId?: string;
    /**
     * Client secret for GCP Vertex AI
     * @type {string}
     * @memberof NLSearchModelBase
     */
    clientSecret?: string;
    /**
     * Region for GCP Vertex AI
     * @type {string}
     * @memberof NLSearchModelBase
     */
    region?: string;
    /**
     * Maximum output tokens for GCP Vertex AI
     * @type {number}
     * @memberof NLSearchModelBase
     */
    maxOutputTokens?: number;
    /**
     * Account ID for Cloudflare-specific models
     * @type {string}
     * @memberof NLSearchModelBase
     */
    accountId?: string;
}

/**
 * Check if a given object implements the NLSearchModelBase interface.
 */
export function instanceOfNLSearchModelBase(value: object): value is NLSearchModelBase {
    return true;
}

export function NLSearchModelBaseFromJSON(json: any): NLSearchModelBase {
    return NLSearchModelBaseFromJSONTyped(json, false);
}

export function NLSearchModelBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NLSearchModelBase {
    if (json == null) {
        return json;
    }
    return {
        
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'apiUrl': json['api_url'] == null ? undefined : json['api_url'],
        'maxBytes': json['max_bytes'] == null ? undefined : json['max_bytes'],
        'temperature': json['temperature'] == null ? undefined : json['temperature'],
        'systemPrompt': json['system_prompt'] == null ? undefined : json['system_prompt'],
        'topP': json['top_p'] == null ? undefined : json['top_p'],
        'topK': json['top_k'] == null ? undefined : json['top_k'],
        'stopSequences': json['stop_sequences'] == null ? undefined : json['stop_sequences'],
        'apiVersion': json['api_version'] == null ? undefined : json['api_version'],
        'projectId': json['project_id'] == null ? undefined : json['project_id'],
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'clientSecret': json['client_secret'] == null ? undefined : json['client_secret'],
        'region': json['region'] == null ? undefined : json['region'],
        'maxOutputTokens': json['max_output_tokens'] == null ? undefined : json['max_output_tokens'],
        'accountId': json['account_id'] == null ? undefined : json['account_id'],
    };
}

export function NLSearchModelBaseToJSON(json: any): NLSearchModelBase {
    return NLSearchModelBaseToJSONTyped(json, false);
}

export function NLSearchModelBaseToJSONTyped(value?: NLSearchModelBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_name': value['modelName'],
        'api_key': value['apiKey'],
        'api_url': value['apiUrl'],
        'max_bytes': value['maxBytes'],
        'temperature': value['temperature'],
        'system_prompt': value['systemPrompt'],
        'top_p': value['topP'],
        'top_k': value['topK'],
        'stop_sequences': value['stopSequences'],
        'api_version': value['apiVersion'],
        'project_id': value['projectId'],
        'access_token': value['accessToken'],
        'refresh_token': value['refreshToken'],
        'client_id': value['clientId'],
        'client_secret': value['clientSecret'],
        'region': value['region'],
        'max_output_tokens': value['maxOutputTokens'],
        'account_id': value['accountId'],
    };
}

