/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MultiSearchSearchesParameter } from './MultiSearchSearchesParameter';
import {
    instanceOfMultiSearchSearchesParameter,
    MultiSearchSearchesParameterFromJSON,
    MultiSearchSearchesParameterFromJSONTyped,
    MultiSearchSearchesParameterToJSON,
} from './MultiSearchSearchesParameter';
import type { SearchParameters } from './SearchParameters';
import {
    instanceOfSearchParameters,
    SearchParametersFromJSON,
    SearchParametersFromJSONTyped,
    SearchParametersToJSON,
} from './SearchParameters';

/**
 * @type PresetUpsertSchemaValue
 * 
 * @export
 */
export type PresetUpsertSchemaValue = MultiSearchSearchesParameter | SearchParameters;

export function PresetUpsertSchemaValueFromJSON(json: any): PresetUpsertSchemaValue {
    return PresetUpsertSchemaValueFromJSONTyped(json, false);
}

export function PresetUpsertSchemaValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetUpsertSchemaValue {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfMultiSearchSearchesParameter(json)) {
        return MultiSearchSearchesParameterFromJSONTyped(json, true);
    }
    if (instanceOfSearchParameters(json)) {
        return SearchParametersFromJSONTyped(json, true);
    }
    return {} as any;
}

export function PresetUpsertSchemaValueToJSON(json: any): any {
    return PresetUpsertSchemaValueToJSONTyped(json, false);
}

export function PresetUpsertSchemaValueToJSONTyped(value?: PresetUpsertSchemaValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfMultiSearchSearchesParameter(value)) {
        return MultiSearchSearchesParameterToJSON(value as MultiSearchSearchesParameter);
    }
    if (instanceOfSearchParameters(value)) {
        return SearchParametersToJSON(value as SearchParameters);
    }
    return {};
}

