/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PresetSchema } from './PresetSchema';
import {
    PresetSchemaFromJSON,
    PresetSchemaFromJSONTyped,
    PresetSchemaToJSON,
    PresetSchemaToJSONTyped,
} from './PresetSchema';

/**
 * 
 * @export
 * @interface PresetsRetrieveSchema
 */
export interface PresetsRetrieveSchema {
    /**
     * 
     * @type {Array<PresetSchema>}
     * @memberof PresetsRetrieveSchema
     */
    presets: Array<PresetSchema>;
}

/**
 * Check if a given object implements the PresetsRetrieveSchema interface.
 */
export function instanceOfPresetsRetrieveSchema(value: object): value is PresetsRetrieveSchema {
    if (!('presets' in value) || value['presets'] === undefined) return false;
    return true;
}

export function PresetsRetrieveSchemaFromJSON(json: any): PresetsRetrieveSchema {
    return PresetsRetrieveSchemaFromJSONTyped(json, false);
}

export function PresetsRetrieveSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PresetsRetrieveSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'presets': ((json['presets'] as Array<any>).map(PresetSchemaFromJSON)),
    };
}

export function PresetsRetrieveSchemaToJSON(json: any): PresetsRetrieveSchema {
    return PresetsRetrieveSchemaToJSONTyped(json, false);
}

export function PresetsRetrieveSchemaToJSONTyped(value?: PresetsRetrieveSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'presets': ((value['presets'] as Array<any>).map(PresetSchemaToJSON)),
    };
}

