/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaChangeStatus
 */
export interface SchemaChangeStatus {
    /**
     * Name of the collection being modified
     * @type {string}
     * @memberof SchemaChangeStatus
     */
    collection?: string;
    /**
     * Number of documents that have been validated
     * @type {number}
     * @memberof SchemaChangeStatus
     */
    validatedDocs?: number;
    /**
     * Number of documents that have been altered
     * @type {number}
     * @memberof SchemaChangeStatus
     */
    alteredDocs?: number;
}

/**
 * Check if a given object implements the SchemaChangeStatus interface.
 */
export function instanceOfSchemaChangeStatus(value: object): value is SchemaChangeStatus {
    return true;
}

export function SchemaChangeStatusFromJSON(json: any): SchemaChangeStatus {
    return SchemaChangeStatusFromJSONTyped(json, false);
}

export function SchemaChangeStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaChangeStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'] == null ? undefined : json['collection'],
        'validatedDocs': json['validated_docs'] == null ? undefined : json['validated_docs'],
        'alteredDocs': json['altered_docs'] == null ? undefined : json['altered_docs'],
    };
}

export function SchemaChangeStatusToJSON(json: any): SchemaChangeStatus {
    return SchemaChangeStatusToJSONTyped(json, false);
}

export function SchemaChangeStatusToJSONTyped(value?: SchemaChangeStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'validated_docs': value['validatedDocs'],
        'altered_docs': value['alteredDocs'],
    };
}

