/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchOverrideAllOf
 */
export interface SearchOverrideAllOf {
    /**
     * 
     * @type {string}
     * @memberof SearchOverrideAllOf
     */
    readonly id: string;
}

/**
 * Check if a given object implements the SearchOverrideAllOf interface.
 */
export function instanceOfSearchOverrideAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SearchOverrideAllOfFromJSON(json: any): SearchOverrideAllOf {
    return SearchOverrideAllOfFromJSONTyped(json, false);
}

export function SearchOverrideAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOverrideAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SearchOverrideAllOfToJSON(value?: SearchOverrideAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

