/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchSynonymSchema
 */
export interface SearchSynonymSchema {
    /**
     * For 1-way synonyms, indicates the root word that words in the `synonyms` parameter map to.
     * @type {string}
     * @memberof SearchSynonymSchema
     */
    root?: string;
    /**
     * Array of words that should be considered as synonyms.
     * @type {Array<string>}
     * @memberof SearchSynonymSchema
     */
    synonyms: Array<string>;
    /**
     * Locale for the synonym, leave blank to use the standard tokenizer.
     * @type {string}
     * @memberof SearchSynonymSchema
     */
    locale?: string;
    /**
     * By default, special characters are dropped from synonyms. Use this attribute to specify which special characters should be indexed as is.
     * @type {Array<string>}
     * @memberof SearchSynonymSchema
     */
    symbolsToIndex?: Array<string>;
}

/**
 * Check if a given object implements the SearchSynonymSchema interface.
 */
export function instanceOfSearchSynonymSchema(value: object): value is SearchSynonymSchema {
    if (!('synonyms' in value) || value['synonyms'] === undefined) return false;
    return true;
}

export function SearchSynonymSchemaFromJSON(json: any): SearchSynonymSchema {
    return SearchSynonymSchemaFromJSONTyped(json, false);
}

export function SearchSynonymSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSynonymSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'root': json['root'] == null ? undefined : json['root'],
        'synonyms': json['synonyms'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'symbolsToIndex': json['symbols_to_index'] == null ? undefined : json['symbols_to_index'],
    };
}

export function SearchSynonymSchemaToJSON(json: any): SearchSynonymSchema {
    return SearchSynonymSchemaToJSONTyped(json, false);
}

export function SearchSynonymSchemaToJSONTyped(value?: SearchSynonymSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'root': value['root'],
        'synonyms': value['synonyms'],
        'locale': value['locale'],
        'symbols_to_index': value['symbolsToIndex'],
    };
}

