/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResultHitTextMatchInfo } from './SearchResultHitTextMatchInfo';
import {
    SearchResultHitTextMatchInfoFromJSON,
    SearchResultHitTextMatchInfoFromJSONTyped,
    SearchResultHitTextMatchInfoToJSON,
    SearchResultHitTextMatchInfoToJSONTyped,
} from './SearchResultHitTextMatchInfo';
import type { SearchResultHitHybridSearchInfo } from './SearchResultHitHybridSearchInfo';
import {
    SearchResultHitHybridSearchInfoFromJSON,
    SearchResultHitHybridSearchInfoFromJSONTyped,
    SearchResultHitHybridSearchInfoToJSON,
    SearchResultHitHybridSearchInfoToJSONTyped,
} from './SearchResultHitHybridSearchInfo';
import type { SearchHighlight } from './SearchHighlight';
import {
    SearchHighlightFromJSON,
    SearchHighlightFromJSONTyped,
    SearchHighlightToJSON,
    SearchHighlightToJSONTyped,
} from './SearchHighlight';

/**
 * 
 * @export
 * @interface SearchResultHit
 */
export interface SearchResultHit {
    /**
     * (Deprecated) Contains highlighted portions of the search fields
     * @type {Array<SearchHighlight>}
     * @memberof SearchResultHit
     */
    highlights?: Array<SearchHighlight>;
    /**
     * Highlighted version of the matching document
     * @type {{ [key: string]: any; }}
     * @memberof SearchResultHit
     */
    highlight?: { [key: string]: any; };
    /**
     * Can be any key-value pair
     * @type {{ [key: string]: object; }}
     * @memberof SearchResultHit
     */
    document?: { [key: string]: object; };
    /**
     * 
     * @type {number}
     * @memberof SearchResultHit
     */
    textMatch?: number;
    /**
     * 
     * @type {SearchResultHitTextMatchInfo}
     * @memberof SearchResultHit
     */
    textMatchInfo?: SearchResultHitTextMatchInfo;
    /**
     * Can be any key-value pair
     * @type {{ [key: string]: number; }}
     * @memberof SearchResultHit
     */
    geoDistanceMeters?: { [key: string]: number; };
    /**
     * Distance between the query vector and matching document's vector value
     * @type {number}
     * @memberof SearchResultHit
     */
    vectorDistance?: number;
    /**
     * 
     * @type {SearchResultHitHybridSearchInfo}
     * @memberof SearchResultHit
     */
    hybridSearchInfo?: SearchResultHitHybridSearchInfo;
    /**
     * Returned only for union query response. Indicates the index of the query which this document matched to.
     * @type {number}
     * @memberof SearchResultHit
     */
    searchIndex?: number;
}

/**
 * Check if a given object implements the SearchResultHit interface.
 */
export function instanceOfSearchResultHit(value: object): value is SearchResultHit {
    return true;
}

export function SearchResultHitFromJSON(json: any): SearchResultHit {
    return SearchResultHitFromJSONTyped(json, false);
}

export function SearchResultHitFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultHit {
    if (json == null) {
        return json;
    }
    return {
        
        'highlights': json['highlights'] == null ? undefined : ((json['highlights'] as Array<any>).map(SearchHighlightFromJSON)),
        'highlight': json['highlight'] == null ? undefined : json['highlight'],
        'document': json['document'] == null ? undefined : json['document'],
        'textMatch': json['text_match'] == null ? undefined : json['text_match'],
        'textMatchInfo': json['text_match_info'] == null ? undefined : SearchResultHitTextMatchInfoFromJSON(json['text_match_info']),
        'geoDistanceMeters': json['geo_distance_meters'] == null ? undefined : json['geo_distance_meters'],
        'vectorDistance': json['vector_distance'] == null ? undefined : json['vector_distance'],
        'hybridSearchInfo': json['hybrid_search_info'] == null ? undefined : SearchResultHitHybridSearchInfoFromJSON(json['hybrid_search_info']),
        'searchIndex': json['search_index'] == null ? undefined : json['search_index'],
    };
}

export function SearchResultHitToJSON(json: any): SearchResultHit {
    return SearchResultHitToJSONTyped(json, false);
}

export function SearchResultHitToJSONTyped(value?: SearchResultHit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'highlights': value['highlights'] == null ? undefined : ((value['highlights'] as Array<any>).map(SearchHighlightToJSON)),
        'highlight': value['highlight'],
        'document': value['document'],
        'text_match': value['textMatch'],
        'text_match_info': SearchResultHitTextMatchInfoToJSON(value['textMatchInfo']),
        'geo_distance_meters': value['geoDistanceMeters'],
        'vector_distance': value['vectorDistance'],
        'hybrid_search_info': SearchResultHitHybridSearchInfoToJSON(value['hybridSearchInfo']),
        'search_index': value['searchIndex'],
    };
}

