/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchRequestParamsVoiceQuery } from './SearchRequestParamsVoiceQuery';
import {
    SearchRequestParamsVoiceQueryFromJSON,
    SearchRequestParamsVoiceQueryFromJSONTyped,
    SearchRequestParamsVoiceQueryToJSON,
    SearchRequestParamsVoiceQueryToJSONTyped,
} from './SearchRequestParamsVoiceQuery';

/**
 * 
 * @export
 * @interface SearchRequestParams
 */
export interface SearchRequestParams {
    /**
     * 
     * @type {string}
     * @memberof SearchRequestParams
     */
    collectionName: string;
    /**
     * 
     * @type {string}
     * @memberof SearchRequestParams
     */
    q: string;
    /**
     * 
     * @type {number}
     * @memberof SearchRequestParams
     */
    perPage: number;
    /**
     * 
     * @type {SearchRequestParamsVoiceQuery}
     * @memberof SearchRequestParams
     */
    voiceQuery?: SearchRequestParamsVoiceQuery;
}

/**
 * Check if a given object implements the SearchRequestParams interface.
 */
export function instanceOfSearchRequestParams(value: object): value is SearchRequestParams {
    if (!('collectionName' in value) || value['collectionName'] === undefined) return false;
    if (!('q' in value) || value['q'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    return true;
}

export function SearchRequestParamsFromJSON(json: any): SearchRequestParams {
    return SearchRequestParamsFromJSONTyped(json, false);
}

export function SearchRequestParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchRequestParams {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionName': json['collection_name'],
        'q': json['q'],
        'perPage': json['per_page'],
        'voiceQuery': json['voice_query'] == null ? undefined : SearchRequestParamsVoiceQueryFromJSON(json['voice_query']),
    };
}

export function SearchRequestParamsToJSON(json: any): SearchRequestParams {
    return SearchRequestParamsToJSONTyped(json, false);
}

export function SearchRequestParamsToJSONTyped(value?: SearchRequestParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection_name': value['collectionName'],
        'q': value['q'],
        'per_page': value['perPage'],
        'voice_query': SearchRequestParamsVoiceQueryToJSON(value['voiceQuery']),
    };
}

