/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about hybrid search scoring
 * @export
 * @interface SearchResultHitHybridSearchInfo
 */
export interface SearchResultHitHybridSearchInfo {
    /**
     * Combined score from rank fusion of text and vector search
     * @type {number}
     * @memberof SearchResultHitHybridSearchInfo
     */
    rankFusionScore?: number;
}

/**
 * Check if a given object implements the SearchResultHitHybridSearchInfo interface.
 */
export function instanceOfSearchResultHitHybridSearchInfo(value: object): value is SearchResultHitHybridSearchInfo {
    return true;
}

export function SearchResultHitHybridSearchInfoFromJSON(json: any): SearchResultHitHybridSearchInfo {
    return SearchResultHitHybridSearchInfoFromJSONTyped(json, false);
}

export function SearchResultHitHybridSearchInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultHitHybridSearchInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'rankFusionScore': json['rank_fusion_score'] == null ? undefined : json['rank_fusion_score'],
    };
}

export function SearchResultHitHybridSearchInfoToJSON(json: any): SearchResultHitHybridSearchInfo {
    return SearchResultHitHybridSearchInfoToJSONTyped(json, false);
}

export function SearchResultHitHybridSearchInfoToJSONTyped(value?: SearchResultHitHybridSearchInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank_fusion_score': value['rankFusionScore'],
    };
}

