/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchSynonym
 */
export interface SearchSynonym {
    /**
     * For 1-way synonyms, indicates the root word that words in the `synonyms` parameter map to.
     * @type {string}
     * @memberof SearchSynonym
     */
    root?: string;
    /**
     * Array of words that should be considered as synonyms.
     * @type {Array<string>}
     * @memberof SearchSynonym
     */
    synonyms: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SearchSynonym
     */
    readonly id: string;
}

/**
 * Check if a given object implements the SearchSynonym interface.
 */
export function instanceOfSearchSynonym(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "synonyms" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SearchSynonymFromJSON(json: any): SearchSynonym {
    return SearchSynonymFromJSONTyped(json, false);
}

export function SearchSynonymFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSynonym {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'root': !exists(json, 'root') ? undefined : json['root'],
        'synonyms': json['synonyms'],
        'id': json['id'],
    };
}

export function SearchSynonymToJSON(value?: SearchSynonym | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'root': value.root,
        'synonyms': value.synonyms,
    };
}

