/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchSynonym } from './SearchSynonym';
import {
    SearchSynonymFromJSON,
    SearchSynonymFromJSONTyped,
    SearchSynonymToJSON,
    SearchSynonymToJSONTyped,
} from './SearchSynonym';

/**
 * 
 * @export
 * @interface SearchSynonymsResponse
 */
export interface SearchSynonymsResponse {
    /**
     * 
     * @type {Array<SearchSynonym>}
     * @memberof SearchSynonymsResponse
     */
    synonyms: Array<SearchSynonym>;
}

/**
 * Check if a given object implements the SearchSynonymsResponse interface.
 */
export function instanceOfSearchSynonymsResponse(value: object): value is SearchSynonymsResponse {
    if (!('synonyms' in value) || value['synonyms'] === undefined) return false;
    return true;
}

export function SearchSynonymsResponseFromJSON(json: any): SearchSynonymsResponse {
    return SearchSynonymsResponseFromJSONTyped(json, false);
}

export function SearchSynonymsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSynonymsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'synonyms': ((json['synonyms'] as Array<any>).map(SearchSynonymFromJSON)),
    };
}

export function SearchSynonymsResponseToJSON(json: any): SearchSynonymsResponse {
    return SearchSynonymsResponseToJSONTyped(json, false);
}

export function SearchSynonymsResponseToJSONTyped(value?: SearchSynonymsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'synonyms': ((value['synonyms'] as Array<any>).map(SearchSynonymToJSON)),
    };
}

