/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchRequestParams } from './SearchRequestParams';
import {
    SearchRequestParamsFromJSON,
    SearchRequestParamsFromJSONTyped,
    SearchRequestParamsToJSON,
    SearchRequestParamsToJSONTyped,
} from './SearchRequestParams';
import type { SearchGroupedHit } from './SearchGroupedHit';
import {
    SearchGroupedHitFromJSON,
    SearchGroupedHitFromJSONTyped,
    SearchGroupedHitToJSON,
    SearchGroupedHitToJSONTyped,
} from './SearchGroupedHit';
import type { SearchResultConversation } from './SearchResultConversation';
import {
    SearchResultConversationFromJSON,
    SearchResultConversationFromJSONTyped,
    SearchResultConversationToJSON,
    SearchResultConversationToJSONTyped,
} from './SearchResultConversation';
import type { SearchResultHit } from './SearchResultHit';
import {
    SearchResultHitFromJSON,
    SearchResultHitFromJSONTyped,
    SearchResultHitToJSON,
    SearchResultHitToJSONTyped,
} from './SearchResultHit';
import type { FacetCounts } from './FacetCounts';
import {
    FacetCountsFromJSON,
    FacetCountsFromJSONTyped,
    FacetCountsToJSON,
    FacetCountsToJSONTyped,
} from './FacetCounts';

/**
 * 
 * @export
 * @interface SearchResult
 */
export interface SearchResult {
    /**
     * 
     * @type {Array<FacetCounts>}
     * @memberof SearchResult
     */
    facetCounts?: Array<FacetCounts>;
    /**
     * The number of documents found
     * @type {number}
     * @memberof SearchResult
     */
    found?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchResult
     */
    foundDocs?: number;
    /**
     * The number of milliseconds the search took
     * @type {number}
     * @memberof SearchResult
     */
    searchTimeMs?: number;
    /**
     * The total number of documents in the collection
     * @type {number}
     * @memberof SearchResult
     */
    outOf?: number;
    /**
     * Whether the search was cut off
     * @type {boolean}
     * @memberof SearchResult
     */
    searchCutoff?: boolean;
    /**
     * The search result page number
     * @type {number}
     * @memberof SearchResult
     */
    page?: number;
    /**
     * 
     * @type {Array<SearchGroupedHit>}
     * @memberof SearchResult
     */
    groupedHits?: Array<SearchGroupedHit>;
    /**
     * The documents that matched the search query
     * @type {Array<SearchResultHit>}
     * @memberof SearchResult
     */
    hits?: Array<SearchResultHit>;
    /**
     * 
     * @type {SearchRequestParams}
     * @memberof SearchResult
     */
    requestParams?: SearchRequestParams;
    /**
     * 
     * @type {SearchResultConversation}
     * @memberof SearchResult
     */
    conversation?: SearchResultConversation;
    /**
     * Returned only for union query response.
     * @type {Array<SearchRequestParams>}
     * @memberof SearchResult
     */
    unionRequestParams?: Array<SearchRequestParams>;
    /**
     * Custom JSON object that can be returned in the search response
     * @type {{ [key: string]: any; }}
     * @memberof SearchResult
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SearchResult interface.
 */
export function instanceOfSearchResult(value: object): value is SearchResult {
    return true;
}

export function SearchResultFromJSON(json: any): SearchResult {
    return SearchResultFromJSONTyped(json, false);
}

export function SearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'facetCounts': json['facet_counts'] == null ? undefined : ((json['facet_counts'] as Array<any>).map(FacetCountsFromJSON)),
        'found': json['found'] == null ? undefined : json['found'],
        'foundDocs': json['found_docs'] == null ? undefined : json['found_docs'],
        'searchTimeMs': json['search_time_ms'] == null ? undefined : json['search_time_ms'],
        'outOf': json['out_of'] == null ? undefined : json['out_of'],
        'searchCutoff': json['search_cutoff'] == null ? undefined : json['search_cutoff'],
        'page': json['page'] == null ? undefined : json['page'],
        'groupedHits': json['grouped_hits'] == null ? undefined : ((json['grouped_hits'] as Array<any>).map(SearchGroupedHitFromJSON)),
        'hits': json['hits'] == null ? undefined : ((json['hits'] as Array<any>).map(SearchResultHitFromJSON)),
        'requestParams': json['request_params'] == null ? undefined : SearchRequestParamsFromJSON(json['request_params']),
        'conversation': json['conversation'] == null ? undefined : SearchResultConversationFromJSON(json['conversation']),
        'unionRequestParams': json['union_request_params'] == null ? undefined : ((json['union_request_params'] as Array<any>).map(SearchRequestParamsFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function SearchResultToJSON(json: any): SearchResult {
    return SearchResultToJSONTyped(json, false);
}

export function SearchResultToJSONTyped(value?: SearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'facet_counts': value['facetCounts'] == null ? undefined : ((value['facetCounts'] as Array<any>).map(FacetCountsToJSON)),
        'found': value['found'],
        'found_docs': value['foundDocs'],
        'search_time_ms': value['searchTimeMs'],
        'out_of': value['outOf'],
        'search_cutoff': value['searchCutoff'],
        'page': value['page'],
        'grouped_hits': value['groupedHits'] == null ? undefined : ((value['groupedHits'] as Array<any>).map(SearchGroupedHitToJSON)),
        'hits': value['hits'] == null ? undefined : ((value['hits'] as Array<any>).map(SearchResultHitToJSON)),
        'request_params': SearchRequestParamsToJSON(value['requestParams']),
        'conversation': SearchResultConversationToJSON(value['conversation']),
        'union_request_params': value['unionRequestParams'] == null ? undefined : ((value['unionRequestParams'] as Array<any>).map(SearchRequestParamsToJSON)),
        'metadata': value['metadata'],
    };
}

