/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchResultHitTextMatchInfo
 */
export interface SearchResultHitTextMatchInfo {
    /**
     * 
     * @type {string}
     * @memberof SearchResultHitTextMatchInfo
     */
    bestFieldScore?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchResultHitTextMatchInfo
     */
    bestFieldWeight?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchResultHitTextMatchInfo
     */
    fieldsMatched?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchResultHitTextMatchInfo
     */
    numTokensDropped?: number;
    /**
     * 
     * @type {string}
     * @memberof SearchResultHitTextMatchInfo
     */
    score?: string;
    /**
     * 
     * @type {number}
     * @memberof SearchResultHitTextMatchInfo
     */
    tokensMatched?: number;
    /**
     * 
     * @type {number}
     * @memberof SearchResultHitTextMatchInfo
     */
    typoPrefixScore?: number;
}

/**
 * Check if a given object implements the SearchResultHitTextMatchInfo interface.
 */
export function instanceOfSearchResultHitTextMatchInfo(value: object): value is SearchResultHitTextMatchInfo {
    return true;
}

export function SearchResultHitTextMatchInfoFromJSON(json: any): SearchResultHitTextMatchInfo {
    return SearchResultHitTextMatchInfoFromJSONTyped(json, false);
}

export function SearchResultHitTextMatchInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultHitTextMatchInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'bestFieldScore': json['best_field_score'] == null ? undefined : json['best_field_score'],
        'bestFieldWeight': json['best_field_weight'] == null ? undefined : json['best_field_weight'],
        'fieldsMatched': json['fields_matched'] == null ? undefined : json['fields_matched'],
        'numTokensDropped': json['num_tokens_dropped'] == null ? undefined : json['num_tokens_dropped'],
        'score': json['score'] == null ? undefined : json['score'],
        'tokensMatched': json['tokens_matched'] == null ? undefined : json['tokens_matched'],
        'typoPrefixScore': json['typo_prefix_score'] == null ? undefined : json['typo_prefix_score'],
    };
}

export function SearchResultHitTextMatchInfoToJSON(json: any): SearchResultHitTextMatchInfo {
    return SearchResultHitTextMatchInfoToJSONTyped(json, false);
}

export function SearchResultHitTextMatchInfoToJSONTyped(value?: SearchResultHitTextMatchInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'best_field_score': value['bestFieldScore'],
        'best_field_weight': value['bestFieldWeight'],
        'fields_matched': value['fieldsMatched'],
        'num_tokens_dropped': value['numTokensDropped'],
        'score': value['score'],
        'tokens_matched': value['tokensMatched'],
        'typo_prefix_score': value['typoPrefixScore'],
    };
}

