/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchSynonymDeleteResponse
 */
export interface SearchSynonymDeleteResponse {
    /**
     * The id of the synonym that was deleted
     * @type {string}
     * @memberof SearchSynonymDeleteResponse
     */
    id: string;
}

/**
 * Check if a given object implements the SearchSynonymDeleteResponse interface.
 */
export function instanceOfSearchSynonymDeleteResponse(value: object): value is SearchSynonymDeleteResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SearchSynonymDeleteResponseFromJSON(json: any): SearchSynonymDeleteResponse {
    return SearchSynonymDeleteResponseFromJSONTyped(json, false);
}

export function SearchSynonymDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSynonymDeleteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SearchSynonymDeleteResponseToJSON(json: any): SearchSynonymDeleteResponse {
    return SearchSynonymDeleteResponseToJSONTyped(json, false);
}

export function SearchSynonymDeleteResponseToJSONTyped(value?: SearchSynonymDeleteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

