/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchOverride } from './SearchOverride';
import {
    SearchOverrideFromJSON,
    SearchOverrideFromJSONTyped,
    SearchOverrideToJSON,
} from './SearchOverride';

/**
 * 
 * @export
 * @interface SearchOverridesResponse
 */
export interface SearchOverridesResponse {
    /**
     * 
     * @type {Array<SearchOverride>}
     * @memberof SearchOverridesResponse
     */
    overrides: Array<SearchOverride>;
}

/**
 * Check if a given object implements the SearchOverridesResponse interface.
 */
export function instanceOfSearchOverridesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "overrides" in value;

    return isInstance;
}

export function SearchOverridesResponseFromJSON(json: any): SearchOverridesResponse {
    return SearchOverridesResponseFromJSONTyped(json, false);
}

export function SearchOverridesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOverridesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'overrides': ((json['overrides'] as Array<any>).map(SearchOverrideFromJSON)),
    };
}

export function SearchOverridesResponseToJSON(value?: SearchOverridesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'overrides': ((value.overrides as Array<any>).map(SearchOverrideToJSON)),
    };
}

