/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchOverrideInclude
 */
export interface SearchOverrideInclude {
    /**
     * document id that should be included
     * @type {string}
     * @memberof SearchOverrideInclude
     */
    id: string;
    /**
     * position number where document should be included in the search results
     * @type {number}
     * @memberof SearchOverrideInclude
     */
    position: number;
}

/**
 * Check if a given object implements the SearchOverrideInclude interface.
 */
export function instanceOfSearchOverrideInclude(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "position" in value;

    return isInstance;
}

export function SearchOverrideIncludeFromJSON(json: any): SearchOverrideInclude {
    return SearchOverrideIncludeFromJSONTyped(json, false);
}

export function SearchOverrideIncludeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchOverrideInclude {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'position': json['position'],
    };
}

export function SearchOverrideIncludeToJSON(value?: SearchOverrideInclude | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'position': value.position,
    };
}

