/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchResultHit } from './SearchResultHit';
import {
    SearchResultHitFromJSON,
    SearchResultHitFromJSONTyped,
    SearchResultHitToJSON,
    SearchResultHitToJSONTyped,
} from './SearchResultHit';

/**
 * 
 * @export
 * @interface SearchGroupedHit
 */
export interface SearchGroupedHit {
    /**
     * 
     * @type {number}
     * @memberof SearchGroupedHit
     */
    found?: number;
    /**
     * 
     * @type {Array<any>}
     * @memberof SearchGroupedHit
     */
    groupKey: Array<any>;
    /**
     * The documents that matched the search query
     * @type {Array<SearchResultHit>}
     * @memberof SearchGroupedHit
     */
    hits: Array<SearchResultHit>;
}

/**
 * Check if a given object implements the SearchGroupedHit interface.
 */
export function instanceOfSearchGroupedHit(value: object): value is SearchGroupedHit {
    if (!('groupKey' in value) || value['groupKey'] === undefined) return false;
    if (!('hits' in value) || value['hits'] === undefined) return false;
    return true;
}

export function SearchGroupedHitFromJSON(json: any): SearchGroupedHit {
    return SearchGroupedHitFromJSONTyped(json, false);
}

export function SearchGroupedHitFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchGroupedHit {
    if (json == null) {
        return json;
    }
    return {
        
        'found': json['found'] == null ? undefined : json['found'],
        'groupKey': json['group_key'],
        'hits': ((json['hits'] as Array<any>).map(SearchResultHitFromJSON)),
    };
}

export function SearchGroupedHitToJSON(json: any): SearchGroupedHit {
    return SearchGroupedHitToJSONTyped(json, false);
}

export function SearchGroupedHitToJSONTyped(value?: SearchGroupedHit | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'found': value['found'],
        'group_key': value['groupKey'],
        'hits': ((value['hits'] as Array<any>).map(SearchResultHitToJSON)),
    };
}

