/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.25.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotParameters
 */
export interface SnapshotParameters {
    /**
     * 
     * @type {string}
     * @memberof SnapshotParameters
     */
    snapshotPath?: string;
}

/**
 * Check if a given object implements the SnapshotParameters interface.
 */
export function instanceOfSnapshotParameters(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SnapshotParametersFromJSON(json: any): SnapshotParameters {
    return SnapshotParametersFromJSONTyped(json, false);
}

export function SnapshotParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'snapshotPath': !exists(json, 'snapshot_path') ? undefined : json['snapshot_path'],
    };
}

export function SnapshotParametersToJSON(value?: SnapshotParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'snapshot_path': value.snapshotPath,
    };
}

