/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StemmingDictionaryWordsInner } from './StemmingDictionaryWordsInner';
import {
    StemmingDictionaryWordsInnerFromJSON,
    StemmingDictionaryWordsInnerFromJSONTyped,
    StemmingDictionaryWordsInnerToJSON,
    StemmingDictionaryWordsInnerToJSONTyped,
} from './StemmingDictionaryWordsInner';

/**
 * 
 * @export
 * @interface StemmingDictionary
 */
export interface StemmingDictionary {
    /**
     * Unique identifier for the dictionary
     * @type {string}
     * @memberof StemmingDictionary
     */
    id: string;
    /**
     * List of word mappings in the dictionary
     * @type {Array<StemmingDictionaryWordsInner>}
     * @memberof StemmingDictionary
     */
    words: Array<StemmingDictionaryWordsInner>;
}

/**
 * Check if a given object implements the StemmingDictionary interface.
 */
export function instanceOfStemmingDictionary(value: object): value is StemmingDictionary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('words' in value) || value['words'] === undefined) return false;
    return true;
}

export function StemmingDictionaryFromJSON(json: any): StemmingDictionary {
    return StemmingDictionaryFromJSONTyped(json, false);
}

export function StemmingDictionaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): StemmingDictionary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'words': ((json['words'] as Array<any>).map(StemmingDictionaryWordsInnerFromJSON)),
    };
}

export function StemmingDictionaryToJSON(json: any): StemmingDictionary {
    return StemmingDictionaryToJSONTyped(json, false);
}

export function StemmingDictionaryToJSONTyped(value?: StemmingDictionary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'words': ((value['words'] as Array<any>).map(StemmingDictionaryWordsInnerToJSON)),
    };
}

