/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StemmingDictionaryWordsInner
 */
export interface StemmingDictionaryWordsInner {
    /**
     * The word form to be stemmed
     * @type {string}
     * @memberof StemmingDictionaryWordsInner
     */
    word: string;
    /**
     * The root form of the word
     * @type {string}
     * @memberof StemmingDictionaryWordsInner
     */
    root: string;
}

/**
 * Check if a given object implements the StemmingDictionaryWordsInner interface.
 */
export function instanceOfStemmingDictionaryWordsInner(value: object): value is StemmingDictionaryWordsInner {
    if (!('word' in value) || value['word'] === undefined) return false;
    if (!('root' in value) || value['root'] === undefined) return false;
    return true;
}

export function StemmingDictionaryWordsInnerFromJSON(json: any): StemmingDictionaryWordsInner {
    return StemmingDictionaryWordsInnerFromJSONTyped(json, false);
}

export function StemmingDictionaryWordsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StemmingDictionaryWordsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'word': json['word'],
        'root': json['root'],
    };
}

export function StemmingDictionaryWordsInnerToJSON(json: any): StemmingDictionaryWordsInner {
    return StemmingDictionaryWordsInnerToJSONTyped(json, false);
}

export function StemmingDictionaryWordsInnerToJSONTyped(value?: StemmingDictionaryWordsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'word': value['word'],
        'root': value['root'],
    };
}

