/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StopwordsSetSchema } from './StopwordsSetSchema';
import {
    StopwordsSetSchemaFromJSON,
    StopwordsSetSchemaFromJSONTyped,
    StopwordsSetSchemaToJSON,
    StopwordsSetSchemaToJSONTyped,
} from './StopwordsSetSchema';

/**
 * 
 * @export
 * @interface StopwordsSetRetrieveSchema
 */
export interface StopwordsSetRetrieveSchema {
    /**
     * 
     * @type {StopwordsSetSchema}
     * @memberof StopwordsSetRetrieveSchema
     */
    stopwords: StopwordsSetSchema;
}

/**
 * Check if a given object implements the StopwordsSetRetrieveSchema interface.
 */
export function instanceOfStopwordsSetRetrieveSchema(value: object): value is StopwordsSetRetrieveSchema {
    if (!('stopwords' in value) || value['stopwords'] === undefined) return false;
    return true;
}

export function StopwordsSetRetrieveSchemaFromJSON(json: any): StopwordsSetRetrieveSchema {
    return StopwordsSetRetrieveSchemaFromJSONTyped(json, false);
}

export function StopwordsSetRetrieveSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopwordsSetRetrieveSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'stopwords': StopwordsSetSchemaFromJSON(json['stopwords']),
    };
}

export function StopwordsSetRetrieveSchemaToJSON(json: any): StopwordsSetRetrieveSchema {
    return StopwordsSetRetrieveSchemaToJSONTyped(json, false);
}

export function StopwordsSetRetrieveSchemaToJSONTyped(value?: StopwordsSetRetrieveSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stopwords': StopwordsSetSchemaToJSON(value['stopwords']),
    };
}

