/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StopwordsSetSchema } from './StopwordsSetSchema';
import {
    StopwordsSetSchemaFromJSON,
    StopwordsSetSchemaFromJSONTyped,
    StopwordsSetSchemaToJSON,
    StopwordsSetSchemaToJSONTyped,
} from './StopwordsSetSchema';

/**
 * 
 * @export
 * @interface StopwordsSetsRetrieveAllSchema
 */
export interface StopwordsSetsRetrieveAllSchema {
    /**
     * 
     * @type {Array<StopwordsSetSchema>}
     * @memberof StopwordsSetsRetrieveAllSchema
     */
    stopwords: Array<StopwordsSetSchema>;
}

/**
 * Check if a given object implements the StopwordsSetsRetrieveAllSchema interface.
 */
export function instanceOfStopwordsSetsRetrieveAllSchema(value: object): value is StopwordsSetsRetrieveAllSchema {
    if (!('stopwords' in value) || value['stopwords'] === undefined) return false;
    return true;
}

export function StopwordsSetsRetrieveAllSchemaFromJSON(json: any): StopwordsSetsRetrieveAllSchema {
    return StopwordsSetsRetrieveAllSchemaFromJSONTyped(json, false);
}

export function StopwordsSetsRetrieveAllSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopwordsSetsRetrieveAllSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'stopwords': ((json['stopwords'] as Array<any>).map(StopwordsSetSchemaFromJSON)),
    };
}

export function StopwordsSetsRetrieveAllSchemaToJSON(json: any): StopwordsSetsRetrieveAllSchema {
    return StopwordsSetsRetrieveAllSchemaToJSONTyped(json, false);
}

export function StopwordsSetsRetrieveAllSchemaToJSONTyped(value?: StopwordsSetsRetrieveAllSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stopwords': ((value['stopwords'] as Array<any>).map(StopwordsSetSchemaToJSON)),
    };
}

