/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopwordsSetUpsertSchema
 */
export interface StopwordsSetUpsertSchema {
    /**
     * 
     * @type {Array<string>}
     * @memberof StopwordsSetUpsertSchema
     */
    stopwords: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StopwordsSetUpsertSchema
     */
    locale?: string;
}

/**
 * Check if a given object implements the StopwordsSetUpsertSchema interface.
 */
export function instanceOfStopwordsSetUpsertSchema(value: object): value is StopwordsSetUpsertSchema {
    if (!('stopwords' in value) || value['stopwords'] === undefined) return false;
    return true;
}

export function StopwordsSetUpsertSchemaFromJSON(json: any): StopwordsSetUpsertSchema {
    return StopwordsSetUpsertSchemaFromJSONTyped(json, false);
}

export function StopwordsSetUpsertSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopwordsSetUpsertSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'stopwords': json['stopwords'],
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function StopwordsSetUpsertSchemaToJSON(json: any): StopwordsSetUpsertSchema {
    return StopwordsSetUpsertSchemaToJSONTyped(json, false);
}

export function StopwordsSetUpsertSchemaToJSONTyped(value?: StopwordsSetUpsertSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stopwords': value['stopwords'],
        'locale': value['locale'],
    };
}

