/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StopwordsSetSchema
 */
export interface StopwordsSetSchema {
    /**
     * 
     * @type {string}
     * @memberof StopwordsSetSchema
     */
    id: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StopwordsSetSchema
     */
    stopwords: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof StopwordsSetSchema
     */
    locale?: string;
}

/**
 * Check if a given object implements the StopwordsSetSchema interface.
 */
export function instanceOfStopwordsSetSchema(value: object): value is StopwordsSetSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('stopwords' in value) || value['stopwords'] === undefined) return false;
    return true;
}

export function StopwordsSetSchemaFromJSON(json: any): StopwordsSetSchema {
    return StopwordsSetSchemaFromJSONTyped(json, false);
}

export function StopwordsSetSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): StopwordsSetSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'stopwords': json['stopwords'],
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function StopwordsSetSchemaToJSON(json: any): StopwordsSetSchema {
    return StopwordsSetSchemaToJSONTyped(json, false);
}

export function StopwordsSetSchemaToJSONTyped(value?: StopwordsSetSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'stopwords': value['stopwords'],
        'locale': value['locale'],
    };
}

