/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuccessStatus
 */
export interface SuccessStatus {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessStatus
     */
    success: boolean;
}

/**
 * Check if a given object implements the SuccessStatus interface.
 */
export function instanceOfSuccessStatus(value: object): value is SuccessStatus {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SuccessStatusFromJSON(json: any): SuccessStatus {
    return SuccessStatusFromJSONTyped(json, false);
}

export function SuccessStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SuccessStatusToJSON(json: any): SuccessStatus {
    return SuccessStatusToJSONTyped(json, false);
}

export function SuccessStatusToJSONTyped(value?: SuccessStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

