/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 0.24.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuccessStatus
 */
export interface SuccessStatus {
    /**
     * 
     * @type {boolean}
     * @memberof SuccessStatus
     */
    success: boolean;
}

/**
 * Check if a given object implements the SuccessStatus interface.
 */
export function instanceOfSuccessStatus(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function SuccessStatusFromJSON(json: any): SuccessStatus {
    return SuccessStatusFromJSONTyped(json, false);
}

export function SuccessStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuccessStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function SuccessStatusToJSON(value?: SuccessStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

