/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SynonymItemSchema
 */
export interface SynonymItemSchema {
    /**
     * Array of words that should be considered as synonyms
     * @type {Array<string>}
     * @memberof SynonymItemSchema
     */
    synonyms: Array<string>;
    /**
     * For 1-way synonyms, indicates the root word that words in the synonyms parameter map to
     * @type {string}
     * @memberof SynonymItemSchema
     */
    root?: string;
    /**
     * Locale for the synonym, leave blank to use the standard tokenizer
     * @type {string}
     * @memberof SynonymItemSchema
     */
    locale?: string;
    /**
     * By default, special characters are dropped from synonyms. Use this attribute to specify which special characters should be indexed as is
     * @type {Array<string>}
     * @memberof SynonymItemSchema
     */
    symbolsToIndex?: Array<string>;
    /**
     * Unique identifier for the synonym item
     * @type {string}
     * @memberof SynonymItemSchema
     */
    id: string;
}

/**
 * Check if a given object implements the SynonymItemSchema interface.
 */
export function instanceOfSynonymItemSchema(value: object): value is SynonymItemSchema {
    if (!('synonyms' in value) || value['synonyms'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SynonymItemSchemaFromJSON(json: any): SynonymItemSchema {
    return SynonymItemSchemaFromJSONTyped(json, false);
}

export function SynonymItemSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SynonymItemSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'synonyms': json['synonyms'],
        'root': json['root'] == null ? undefined : json['root'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'symbolsToIndex': json['symbols_to_index'] == null ? undefined : json['symbols_to_index'],
        'id': json['id'],
    };
}

export function SynonymItemSchemaToJSON(json: any): SynonymItemSchema {
    return SynonymItemSchemaToJSONTyped(json, false);
}

export function SynonymItemSchemaToJSONTyped(value?: SynonymItemSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'synonyms': value['synonyms'],
        'root': value['root'],
        'locale': value['locale'],
        'symbols_to_index': value['symbolsToIndex'],
        'id': value['id'],
    };
}

