/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SynonymSetDeleteSchema
 */
export interface SynonymSetDeleteSchema {
    /**
     * Name of the deleted synonym set
     * @type {string}
     * @memberof SynonymSetDeleteSchema
     */
    name: string;
}

/**
 * Check if a given object implements the SynonymSetDeleteSchema interface.
 */
export function instanceOfSynonymSetDeleteSchema(value: object): value is SynonymSetDeleteSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SynonymSetDeleteSchemaFromJSON(json: any): SynonymSetDeleteSchema {
    return SynonymSetDeleteSchemaFromJSONTyped(json, false);
}

export function SynonymSetDeleteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SynonymSetDeleteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SynonymSetDeleteSchemaToJSON(json: any): SynonymSetDeleteSchema {
    return SynonymSetDeleteSchemaToJSONTyped(json, false);
}

export function SynonymSetDeleteSchemaToJSONTyped(value?: SynonymSetDeleteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

