/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SynonymItemSchema } from './SynonymItemSchema';
import {
    SynonymItemSchemaFromJSON,
    SynonymItemSchemaFromJSONTyped,
    SynonymItemSchemaToJSON,
    SynonymItemSchemaToJSONTyped,
} from './SynonymItemSchema';

/**
 * 
 * @export
 * @interface SynonymSetSchema
 */
export interface SynonymSetSchema {
    /**
     * Array of synonym items
     * @type {Array<SynonymItemSchema>}
     * @memberof SynonymSetSchema
     */
    items: Array<SynonymItemSchema>;
    /**
     * Name of the synonym set
     * @type {string}
     * @memberof SynonymSetSchema
     */
    name: string;
}

/**
 * Check if a given object implements the SynonymSetSchema interface.
 */
export function instanceOfSynonymSetSchema(value: object): value is SynonymSetSchema {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SynonymSetSchemaFromJSON(json: any): SynonymSetSchema {
    return SynonymSetSchemaFromJSONTyped(json, false);
}

export function SynonymSetSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SynonymSetSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SynonymItemSchemaFromJSON)),
        'name': json['name'],
    };
}

export function SynonymSetSchemaToJSON(json: any): SynonymSetSchema {
    return SynonymSetSchemaToJSONTyped(json, false);
}

export function SynonymSetSchemaToJSONTyped(value?: SynonymSetSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SynonymItemSchemaToJSON)),
        'name': value['name'],
    };
}

