/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SynonymItemSchema } from './SynonymItemSchema';
import {
    SynonymItemSchemaFromJSON,
    SynonymItemSchemaFromJSONTyped,
    SynonymItemSchemaToJSON,
    SynonymItemSchemaToJSONTyped,
} from './SynonymItemSchema';

/**
 * 
 * @export
 * @interface SynonymSetCreateSchema
 */
export interface SynonymSetCreateSchema {
    /**
     * Array of synonym items
     * @type {Array<SynonymItemSchema>}
     * @memberof SynonymSetCreateSchema
     */
    items: Array<SynonymItemSchema>;
}

/**
 * Check if a given object implements the SynonymSetCreateSchema interface.
 */
export function instanceOfSynonymSetCreateSchema(value: object): value is SynonymSetCreateSchema {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function SynonymSetCreateSchemaFromJSON(json: any): SynonymSetCreateSchema {
    return SynonymSetCreateSchemaFromJSONTyped(json, false);
}

export function SynonymSetCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SynonymSetCreateSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SynonymItemSchemaFromJSON)),
    };
}

export function SynonymSetCreateSchemaToJSON(json: any): SynonymSetCreateSchema {
    return SynonymSetCreateSchemaToJSONTyped(json, false);
}

export function SynonymSetCreateSchemaToJSONTyped(value?: SynonymSetCreateSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SynonymItemSchemaToJSON)),
    };
}

