/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SynonymItemDeleteSchema
 */
export interface SynonymItemDeleteSchema {
    /**
     * ID of the deleted synonym item
     * @type {string}
     * @memberof SynonymItemDeleteSchema
     */
    id: string;
}

/**
 * Check if a given object implements the SynonymItemDeleteSchema interface.
 */
export function instanceOfSynonymItemDeleteSchema(value: object): value is SynonymItemDeleteSchema {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SynonymItemDeleteSchemaFromJSON(json: any): SynonymItemDeleteSchema {
    return SynonymItemDeleteSchemaFromJSONTyped(json, false);
}

export function SynonymItemDeleteSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SynonymItemDeleteSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SynonymItemDeleteSchemaToJSON(json: any): SynonymItemDeleteSchema {
    return SynonymItemDeleteSchemaToJSONTyped(json, false);
}

export function SynonymItemDeleteSchemaToJSONTyped(value?: SynonymItemDeleteSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

