/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleSlowRequestLogRequest
 */
export interface ToggleSlowRequestLogRequest {
    /**
     * 
     * @type {number}
     * @memberof ToggleSlowRequestLogRequest
     */
    logSlowRequestsTimeMs: number;
}

/**
 * Check if a given object implements the ToggleSlowRequestLogRequest interface.
 */
export function instanceOfToggleSlowRequestLogRequest(value: object): value is ToggleSlowRequestLogRequest {
    if (!('logSlowRequestsTimeMs' in value) || value['logSlowRequestsTimeMs'] === undefined) return false;
    return true;
}

export function ToggleSlowRequestLogRequestFromJSON(json: any): ToggleSlowRequestLogRequest {
    return ToggleSlowRequestLogRequestFromJSONTyped(json, false);
}

export function ToggleSlowRequestLogRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleSlowRequestLogRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'logSlowRequestsTimeMs': json['log-slow-requests-time-ms'],
    };
}

export function ToggleSlowRequestLogRequestToJSON(json: any): ToggleSlowRequestLogRequest {
    return ToggleSlowRequestLogRequestToJSONTyped(json, false);
}

export function ToggleSlowRequestLogRequestToJSONTyped(value?: ToggleSlowRequestLogRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'log-slow-requests-time-ms': value['logSlowRequestsTimeMs'],
    };
}

