/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDocumentsUpdateDocumentsParametersParameter
 */
export interface UpdateDocumentsUpdateDocumentsParametersParameter {
    /**
     * 
     * @type {string}
     * @memberof UpdateDocumentsUpdateDocumentsParametersParameter
     */
    filterBy?: string;
}

/**
 * Check if a given object implements the UpdateDocumentsUpdateDocumentsParametersParameter interface.
 */
export function instanceOfUpdateDocumentsUpdateDocumentsParametersParameter(value: object): value is UpdateDocumentsUpdateDocumentsParametersParameter {
    return true;
}

export function UpdateDocumentsUpdateDocumentsParametersParameterFromJSON(json: any): UpdateDocumentsUpdateDocumentsParametersParameter {
    return UpdateDocumentsUpdateDocumentsParametersParameterFromJSONTyped(json, false);
}

export function UpdateDocumentsUpdateDocumentsParametersParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDocumentsUpdateDocumentsParametersParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'filterBy': json['filter_by'] == null ? undefined : json['filter_by'],
    };
}

export function UpdateDocumentsUpdateDocumentsParametersParameterToJSON(json: any): UpdateDocumentsUpdateDocumentsParametersParameter {
    return UpdateDocumentsUpdateDocumentsParametersParameterToJSONTyped(json, false);
}

export function UpdateDocumentsUpdateDocumentsParametersParameterToJSONTyped(value?: UpdateDocumentsUpdateDocumentsParametersParameter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filter_by': value['filterBy'],
    };
}

