/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Configuration for the voice query model
 * 
 * @export
 * @interface VoiceQueryModelCollectionConfig
 */
export interface VoiceQueryModelCollectionConfig {
    /**
     * 
     * @type {string}
     * @memberof VoiceQueryModelCollectionConfig
     */
    modelName?: string;
}

/**
 * Check if a given object implements the VoiceQueryModelCollectionConfig interface.
 */
export function instanceOfVoiceQueryModelCollectionConfig(value: object): value is VoiceQueryModelCollectionConfig {
    return true;
}

export function VoiceQueryModelCollectionConfigFromJSON(json: any): VoiceQueryModelCollectionConfig {
    return VoiceQueryModelCollectionConfigFromJSONTyped(json, false);
}

export function VoiceQueryModelCollectionConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): VoiceQueryModelCollectionConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
    };
}

export function VoiceQueryModelCollectionConfigToJSON(json: any): VoiceQueryModelCollectionConfig {
    return VoiceQueryModelCollectionConfigToJSONTyped(json, false);
}

export function VoiceQueryModelCollectionConfigToJSONTyped(value?: VoiceQueryModelCollectionConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'model_name': value['modelName'],
    };
}

