/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CurationItemCreateSchema,
  CurationItemDeleteSchema,
  CurationItemSchema,
  CurationSetCreateSchema,
  CurationSetDeleteSchema,
  CurationSetSchema,
  ModelApiResponse,
} from '../models/index';
import {
    CurationItemCreateSchemaFromJSON,
    CurationItemCreateSchemaToJSON,
    CurationItemDeleteSchemaFromJSON,
    CurationItemDeleteSchemaToJSON,
    CurationItemSchemaFromJSON,
    CurationItemSchemaToJSON,
    CurationSetCreateSchemaFromJSON,
    CurationSetCreateSchemaToJSON,
    CurationSetDeleteSchemaFromJSON,
    CurationSetDeleteSchemaToJSON,
    CurationSetSchemaFromJSON,
    CurationSetSchemaToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
} from '../models/index';

export interface DeleteCurationSetRequest {
    curationSetName: string;
}

export interface DeleteCurationSetItemRequest {
    curationSetName: string;
    itemId: string;
}

export interface RetrieveCurationSetRequest {
    curationSetName: string;
}

export interface RetrieveCurationSetItemRequest {
    curationSetName: string;
    itemId: string;
}

export interface RetrieveCurationSetItemsRequest {
    curationSetName: string;
}

export interface UpsertCurationSetRequest {
    curationSetName: string;
    curationSetCreateSchema: CurationSetCreateSchema;
}

export interface UpsertCurationSetItemRequest {
    curationSetName: string;
    itemId: string;
    curationItemCreateSchema: CurationItemCreateSchema;
}

/**
 * 
 */
export class CurationSetsApi extends runtime.BaseAPI {

    /**
     * Delete a specific curation set by its name
     * Delete a curation set
     */
    async deleteCurationSetRaw(requestParameters: DeleteCurationSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurationSetDeleteSchema>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling deleteCurationSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurationSetDeleteSchemaFromJSON(jsonValue));
    }

    /**
     * Delete a specific curation set by its name
     * Delete a curation set
     */
    async deleteCurationSet(requestParameters: DeleteCurationSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurationSetDeleteSchema> {
        const response = await this.deleteCurationSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific curation item by its id
     * Delete a curation set item
     */
    async deleteCurationSetItemRaw(requestParameters: DeleteCurationSetItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurationItemDeleteSchema>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling deleteCurationSetItem().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling deleteCurationSetItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}/items/{itemId}`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurationItemDeleteSchemaFromJSON(jsonValue));
    }

    /**
     * Delete a specific curation item by its id
     * Delete a curation set item
     */
    async deleteCurationSetItem(requestParameters: DeleteCurationSetItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurationItemDeleteSchema> {
        const response = await this.deleteCurationSetItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific curation set by its name
     * Retrieve a curation set
     */
    async retrieveCurationSetRaw(requestParameters: RetrieveCurationSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurationSetSchema>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling retrieveCurationSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurationSetSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific curation set by its name
     * Retrieve a curation set
     */
    async retrieveCurationSet(requestParameters: RetrieveCurationSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurationSetSchema> {
        const response = await this.retrieveCurationSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific curation item by its id
     * Retrieve a curation set item
     */
    async retrieveCurationSetItemRaw(requestParameters: RetrieveCurationSetItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurationItemSchema>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling retrieveCurationSetItem().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling retrieveCurationSetItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}/items/{itemId}`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurationItemSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific curation item by its id
     * Retrieve a curation set item
     */
    async retrieveCurationSetItem(requestParameters: RetrieveCurationSetItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurationItemSchema> {
        const response = await this.retrieveCurationSetItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all curation items in a set
     * List items in a curation set
     */
    async retrieveCurationSetItemsRaw(requestParameters: RetrieveCurationSetItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurationItemSchema>>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling retrieveCurationSetItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}/items`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CurationItemSchemaFromJSON));
    }

    /**
     * Retrieve all curation items in a set
     * List items in a curation set
     */
    async retrieveCurationSetItems(requestParameters: RetrieveCurationSetItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurationItemSchema>> {
        const response = await this.retrieveCurationSetItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all curation sets
     * List all curation sets
     */
    async retrieveCurationSetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CurationSetSchema>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CurationSetSchemaFromJSON));
    }

    /**
     * Retrieve all curation sets
     * List all curation sets
     */
    async retrieveCurationSets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CurationSetSchema>> {
        const response = await this.retrieveCurationSetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Create or update a curation set with the given name
     * Create or update a curation set
     */
    async upsertCurationSetRaw(requestParameters: UpsertCurationSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurationSetSchema>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling upsertCurationSet().'
            );
        }

        if (requestParameters['curationSetCreateSchema'] == null) {
            throw new runtime.RequiredError(
                'curationSetCreateSchema',
                'Required parameter "curationSetCreateSchema" was null or undefined when calling upsertCurationSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CurationSetCreateSchemaToJSON(requestParameters['curationSetCreateSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurationSetSchemaFromJSON(jsonValue));
    }

    /**
     * Create or update a curation set with the given name
     * Create or update a curation set
     */
    async upsertCurationSet(requestParameters: UpsertCurationSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurationSetSchema> {
        const response = await this.upsertCurationSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or update a curation set item with the given id
     * Create or update a curation set item
     */
    async upsertCurationSetItemRaw(requestParameters: UpsertCurationSetItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CurationItemSchema>> {
        if (requestParameters['curationSetName'] == null) {
            throw new runtime.RequiredError(
                'curationSetName',
                'Required parameter "curationSetName" was null or undefined when calling upsertCurationSetItem().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling upsertCurationSetItem().'
            );
        }

        if (requestParameters['curationItemCreateSchema'] == null) {
            throw new runtime.RequiredError(
                'curationItemCreateSchema',
                'Required parameter "curationItemCreateSchema" was null or undefined when calling upsertCurationSetItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/curation_sets/{curationSetName}/items/{itemId}`;
        urlPath = urlPath.replace(`{${"curationSetName"}}`, encodeURIComponent(String(requestParameters['curationSetName'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CurationItemCreateSchemaToJSON(requestParameters['curationItemCreateSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CurationItemSchemaFromJSON(jsonValue));
    }

    /**
     * Create or update a curation set item with the given id
     * Create or update a curation set item
     */
    async upsertCurationSetItem(requestParameters: UpsertCurationSetItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CurationItemSchema> {
        const response = await this.upsertCurationSetItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
