/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelApiResponse,
  NLSearchModelCreateSchema,
  NLSearchModelDeleteSchema,
  NLSearchModelSchema,
} from '../models/index';
import {
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    NLSearchModelCreateSchemaFromJSON,
    NLSearchModelCreateSchemaToJSON,
    NLSearchModelDeleteSchemaFromJSON,
    NLSearchModelDeleteSchemaToJSON,
    NLSearchModelSchemaFromJSON,
    NLSearchModelSchemaToJSON,
} from '../models/index';

export interface CreateNLSearchModelRequest {
    nLSearchModelCreateSchema: NLSearchModelCreateSchema;
}

export interface DeleteNLSearchModelRequest {
    modelId: string;
}

export interface RetrieveNLSearchModelRequest {
    modelId: string;
}

export interface UpdateNLSearchModelRequest {
    modelId: string;
    body: NLSearchModelCreateSchema;
}

/**
 * 
 */
export class NlSearchModelsApi extends runtime.BaseAPI {

    /**
     * Create a new NL search model.
     * Create a NL search model
     */
    async createNLSearchModelRaw(requestParameters: CreateNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NLSearchModelSchema>> {
        if (requestParameters['nLSearchModelCreateSchema'] == null) {
            throw new runtime.RequiredError(
                'nLSearchModelCreateSchema',
                'Required parameter "nLSearchModelCreateSchema" was null or undefined when calling createNLSearchModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/nl_search_models`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NLSearchModelCreateSchemaToJSON(requestParameters['nLSearchModelCreateSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NLSearchModelSchemaFromJSON(jsonValue));
    }

    /**
     * Create a new NL search model.
     * Create a NL search model
     */
    async createNLSearchModel(requestParameters: CreateNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NLSearchModelSchema> {
        const response = await this.createNLSearchModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific NL search model by its ID.
     * Delete a NL search model
     */
    async deleteNLSearchModelRaw(requestParameters: DeleteNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NLSearchModelDeleteSchema>> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling deleteNLSearchModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/nl_search_models/{modelId}`;
        urlPath = urlPath.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NLSearchModelDeleteSchemaFromJSON(jsonValue));
    }

    /**
     * Delete a specific NL search model by its ID.
     * Delete a NL search model
     */
    async deleteNLSearchModel(requestParameters: DeleteNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NLSearchModelDeleteSchema> {
        const response = await this.deleteNLSearchModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve all NL search models.
     * List all NL search models
     */
    async retrieveAllNLSearchModelsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<NLSearchModelSchema>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/nl_search_models`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NLSearchModelSchemaFromJSON));
    }

    /**
     * Retrieve all NL search models.
     * List all NL search models
     */
    async retrieveAllNLSearchModels(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<NLSearchModelSchema>> {
        const response = await this.retrieveAllNLSearchModelsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a specific NL search model by its ID.
     * Retrieve a NL search model
     */
    async retrieveNLSearchModelRaw(requestParameters: RetrieveNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NLSearchModelSchema>> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling retrieveNLSearchModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/nl_search_models/{modelId}`;
        urlPath = urlPath.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NLSearchModelSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific NL search model by its ID.
     * Retrieve a NL search model
     */
    async retrieveNLSearchModel(requestParameters: RetrieveNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NLSearchModelSchema> {
        const response = await this.retrieveNLSearchModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an existing NL search model.
     * Update a NL search model
     */
    async updateNLSearchModelRaw(requestParameters: UpdateNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NLSearchModelSchema>> {
        if (requestParameters['modelId'] == null) {
            throw new runtime.RequiredError(
                'modelId',
                'Required parameter "modelId" was null or undefined when calling updateNLSearchModel().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling updateNLSearchModel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/nl_search_models/{modelId}`;
        urlPath = urlPath.replace(`{${"modelId"}}`, encodeURIComponent(String(requestParameters['modelId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NLSearchModelSchemaFromJSON(jsonValue));
    }

    /**
     * Update an existing NL search model.
     * Update a NL search model
     */
    async updateNLSearchModel(requestParameters: UpdateNLSearchModelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NLSearchModelSchema> {
        const response = await this.updateNLSearchModelRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
