/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ModelApiResponse,
  PresetDeleteSchema,
  PresetSchema,
  PresetUpsertSchema,
  PresetsRetrieveSchema,
} from '../models/index';
import {
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    PresetDeleteSchemaFromJSON,
    PresetDeleteSchemaToJSON,
    PresetSchemaFromJSON,
    PresetSchemaToJSON,
    PresetUpsertSchemaFromJSON,
    PresetUpsertSchemaToJSON,
    PresetsRetrieveSchemaFromJSON,
    PresetsRetrieveSchemaToJSON,
} from '../models/index';

export interface DeletePresetRequest {
    presetId: string;
}

export interface RetrievePresetRequest {
    presetId: string;
}

export interface UpsertPresetRequest {
    presetId: string;
    presetUpsertSchema: PresetUpsertSchema;
}

/**
 * 
 */
export class PresetsApi extends runtime.BaseAPI {

    /**
     * Permanently deletes a preset, given it\'s name.
     * Delete a preset.
     */
    async deletePresetRaw(requestParameters: DeletePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetDeleteSchema>> {
        if (requestParameters['presetId'] == null) {
            throw new runtime.RequiredError(
                'presetId',
                'Required parameter "presetId" was null or undefined when calling deletePreset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/presets/{presetId}`;
        urlPath = urlPath.replace(`{${"presetId"}}`, encodeURIComponent(String(requestParameters['presetId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetDeleteSchemaFromJSON(jsonValue));
    }

    /**
     * Permanently deletes a preset, given it\'s name.
     * Delete a preset.
     */
    async deletePreset(requestParameters: DeletePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetDeleteSchema> {
        const response = await this.deletePresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the details of all presets
     * Retrieves all presets.
     */
    async retrieveAllPresetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetsRetrieveSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/presets`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetsRetrieveSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve the details of all presets
     * Retrieves all presets.
     */
    async retrieveAllPresets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetsRetrieveSchema> {
        const response = await this.retrieveAllPresetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the details of a preset, given it\'s name.
     * Retrieves a preset.
     */
    async retrievePresetRaw(requestParameters: RetrievePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetSchema>> {
        if (requestParameters['presetId'] == null) {
            throw new runtime.RequiredError(
                'presetId',
                'Required parameter "presetId" was null or undefined when calling retrievePreset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/presets/{presetId}`;
        urlPath = urlPath.replace(`{${"presetId"}}`, encodeURIComponent(String(requestParameters['presetId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve the details of a preset, given it\'s name.
     * Retrieves a preset.
     */
    async retrievePreset(requestParameters: RetrievePresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetSchema> {
        const response = await this.retrievePresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create or update an existing preset.
     * Upserts a preset.
     */
    async upsertPresetRaw(requestParameters: UpsertPresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PresetSchema>> {
        if (requestParameters['presetId'] == null) {
            throw new runtime.RequiredError(
                'presetId',
                'Required parameter "presetId" was null or undefined when calling upsertPreset().'
            );
        }

        if (requestParameters['presetUpsertSchema'] == null) {
            throw new runtime.RequiredError(
                'presetUpsertSchema',
                'Required parameter "presetUpsertSchema" was null or undefined when calling upsertPreset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/presets/{presetId}`;
        urlPath = urlPath.replace(`{${"presetId"}}`, encodeURIComponent(String(requestParameters['presetId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PresetUpsertSchemaToJSON(requestParameters['presetUpsertSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PresetSchemaFromJSON(jsonValue));
    }

    /**
     * Create or update an existing preset.
     * Upserts a preset.
     */
    async upsertPreset(requestParameters: UpsertPresetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PresetSchema> {
        const response = await this.upsertPresetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
