/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListStemmingDictionaries200Response,
  ModelApiResponse,
  StemmingDictionary,
} from '../models/index';
import {
    ListStemmingDictionaries200ResponseFromJSON,
    ListStemmingDictionaries200ResponseToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    StemmingDictionaryFromJSON,
    StemmingDictionaryToJSON,
} from '../models/index';

export interface GetStemmingDictionaryRequest {
    dictionaryId: string;
}

export interface ImportStemmingDictionaryRequest {
    id: string;
    body: string;
}

/**
 * 
 */
export class StemmingApi extends runtime.BaseAPI {

    /**
     * Fetch details of a specific stemming dictionary.
     * Retrieve a stemming dictionary
     */
    async getStemmingDictionaryRaw(requestParameters: GetStemmingDictionaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StemmingDictionary>> {
        if (requestParameters['dictionaryId'] == null) {
            throw new runtime.RequiredError(
                'dictionaryId',
                'Required parameter "dictionaryId" was null or undefined when calling getStemmingDictionary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stemming/dictionaries/{dictionaryId}`;
        urlPath = urlPath.replace(`{${"dictionaryId"}}`, encodeURIComponent(String(requestParameters['dictionaryId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StemmingDictionaryFromJSON(jsonValue));
    }

    /**
     * Fetch details of a specific stemming dictionary.
     * Retrieve a stemming dictionary
     */
    async getStemmingDictionary(requestParameters: GetStemmingDictionaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StemmingDictionary> {
        const response = await this.getStemmingDictionaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a JSONL file containing word mappings to create or update a stemming dictionary.
     * Import a stemming dictionary
     */
    async importStemmingDictionaryRaw(requestParameters: ImportStemmingDictionaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling importStemmingDictionary().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling importStemmingDictionary().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stemming/dictionaries/import`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Upload a JSONL file containing word mappings to create or update a stemming dictionary.
     * Import a stemming dictionary
     */
    async importStemmingDictionary(requestParameters: ImportStemmingDictionaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.importStemmingDictionaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a list of all available stemming dictionaries.
     * List all stemming dictionaries
     */
    async listStemmingDictionariesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStemmingDictionaries200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stemming/dictionaries`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListStemmingDictionaries200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of all available stemming dictionaries.
     * List all stemming dictionaries
     */
    async listStemmingDictionaries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStemmingDictionaries200Response> {
        const response = await this.listStemmingDictionariesRaw(initOverrides);
        return await response.value();
    }

}
