/* tslint:disable */
/* eslint-disable */
/**
 * Typesense API
 * An open source search engine for building delightful search experiences.
 *
 * The version of the OpenAPI document: 30.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DeleteStopwordsSet200Response,
  ModelApiResponse,
  StopwordsSetRetrieveSchema,
  StopwordsSetSchema,
  StopwordsSetUpsertSchema,
  StopwordsSetsRetrieveAllSchema,
} from '../models/index';
import {
    DeleteStopwordsSet200ResponseFromJSON,
    DeleteStopwordsSet200ResponseToJSON,
    ModelApiResponseFromJSON,
    ModelApiResponseToJSON,
    StopwordsSetRetrieveSchemaFromJSON,
    StopwordsSetRetrieveSchemaToJSON,
    StopwordsSetSchemaFromJSON,
    StopwordsSetSchemaToJSON,
    StopwordsSetUpsertSchemaFromJSON,
    StopwordsSetUpsertSchemaToJSON,
    StopwordsSetsRetrieveAllSchemaFromJSON,
    StopwordsSetsRetrieveAllSchemaToJSON,
} from '../models/index';

export interface DeleteStopwordsSetRequest {
    setId: string;
}

export interface RetrieveStopwordsSetRequest {
    setId: string;
}

export interface UpsertStopwordsSetRequest {
    setId: string;
    stopwordsSetUpsertSchema: StopwordsSetUpsertSchema;
}

/**
 * 
 */
export class StopwordsApi extends runtime.BaseAPI {

    /**
     * Permanently deletes a stopwords set, given it\'s name.
     * Delete a stopwords set.
     */
    async deleteStopwordsSetRaw(requestParameters: DeleteStopwordsSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteStopwordsSet200Response>> {
        if (requestParameters['setId'] == null) {
            throw new runtime.RequiredError(
                'setId',
                'Required parameter "setId" was null or undefined when calling deleteStopwordsSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stopwords/{setId}`;
        urlPath = urlPath.replace(`{${"setId"}}`, encodeURIComponent(String(requestParameters['setId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteStopwordsSet200ResponseFromJSON(jsonValue));
    }

    /**
     * Permanently deletes a stopwords set, given it\'s name.
     * Delete a stopwords set.
     */
    async deleteStopwordsSet(requestParameters: DeleteStopwordsSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteStopwordsSet200Response> {
        const response = await this.deleteStopwordsSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the details of a stopwords set, given it\'s name.
     * Retrieves a stopwords set.
     */
    async retrieveStopwordsSetRaw(requestParameters: RetrieveStopwordsSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopwordsSetRetrieveSchema>> {
        if (requestParameters['setId'] == null) {
            throw new runtime.RequiredError(
                'setId',
                'Required parameter "setId" was null or undefined when calling retrieveStopwordsSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stopwords/{setId}`;
        urlPath = urlPath.replace(`{${"setId"}}`, encodeURIComponent(String(requestParameters['setId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopwordsSetRetrieveSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve the details of a stopwords set, given it\'s name.
     * Retrieves a stopwords set.
     */
    async retrieveStopwordsSet(requestParameters: RetrieveStopwordsSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopwordsSetRetrieveSchema> {
        const response = await this.retrieveStopwordsSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve the details of all stopwords sets
     * Retrieves all stopwords sets.
     */
    async retrieveStopwordsSetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopwordsSetsRetrieveAllSchema>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stopwords`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopwordsSetsRetrieveAllSchemaFromJSON(jsonValue));
    }

    /**
     * Retrieve the details of all stopwords sets
     * Retrieves all stopwords sets.
     */
    async retrieveStopwordsSets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopwordsSetsRetrieveAllSchema> {
        const response = await this.retrieveStopwordsSetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * When an analytics rule is created, we give it a name and describe the type, the source collections and the destination collection.
     * Upserts a stopwords set.
     */
    async upsertStopwordsSetRaw(requestParameters: UpsertStopwordsSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StopwordsSetSchema>> {
        if (requestParameters['setId'] == null) {
            throw new runtime.RequiredError(
                'setId',
                'Required parameter "setId" was null or undefined when calling upsertStopwordsSet().'
            );
        }

        if (requestParameters['stopwordsSetUpsertSchema'] == null) {
            throw new runtime.RequiredError(
                'stopwordsSetUpsertSchema',
                'Required parameter "stopwordsSetUpsertSchema" was null or undefined when calling upsertStopwordsSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-TYPESENSE-API-KEY"] = await this.configuration.apiKey("X-TYPESENSE-API-KEY"); // api_key_header authentication
        }


        let urlPath = `/stopwords/{setId}`;
        urlPath = urlPath.replace(`{${"setId"}}`, encodeURIComponent(String(requestParameters['setId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: StopwordsSetUpsertSchemaToJSON(requestParameters['stopwordsSetUpsertSchema']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StopwordsSetSchemaFromJSON(jsonValue));
    }

    /**
     * When an analytics rule is created, we give it a name and describe the type, the source collections and the destination collection.
     * Upserts a stopwords set.
     */
    async upsertStopwordsSet(requestParameters: UpsertStopwordsSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StopwordsSetSchema> {
        const response = await this.upsertStopwordsSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
